### ISSUE TITLE
웹뷰에서 아임포트 실행시 외부 앱이 열리지 않습니다

### ISSUE THREAD

**Issue by Army-92** [iamport/iamport-react-native#10]
# 아임포트는 이미 웹상에서 연동하여 사용중입니다.
RN 상에서 웹뷰를 통해서 결제를 확인하는 과정중에 에러가 발생하여 이렇게 글을 남깁니다.
(KB국민카드, 카카오 결제 / 안드로이드 기기로 테스트)

![kakaotalk_photo_2019-02-22-16-19-23](https://user-images.githubusercontent.com/29420674/53226298-f8a82a00-36bd-11e9-9641-86b0c5d14e79.jpeg)

![kakaotalk_photo_2019-02-22-16-19-40](https://user-images.githubusercontent.com/29420674/53226453-62283880-36be-11e9-8d27-869f8298cabf.jpeg)

웹뷰상에서 해당 과정까지는 넘어가는데는 문제가 없는데
확인을 누르고 다음과정에서 ISP 실행과정에서 에러가 발생한듯 보여집니다.
(사진상에 ISP 앱은 이미 설치한 상태)

![kakaotalk_photo_2019-02-22-16-19-34](https://user-images.githubusercontent.com/29420674/53226532-a4ea1080-36be-11e9-99c8-28c2c851f52b.jpeg)

삼성카드로 결제 테스트 진행 시에는
![kakaotalk_photo_2019-02-22-16-29-20](https://user-images.githubusercontent.com/29420674/53226637-0611e400-36bf-11e9-9bc0-283931aed449.jpeg)

앱카드 실행을 눌렀을 경우 아무런 반응이 없습니다.

리엑트 네이티브 경우 숙련도가 높지 못해서... 해당 모듈 설치 후 어떻게 해야 될지 방향을 못잡고 있습니다ㅠㅠ
예제를 보니 리엑트 네이티브 내부 컴포넌트 상에서 결제가 이루어져서 webview 안에서 결제가 이루어 지는 경우 어떻게 해야되는지 모르겠습니다 실력이 미숙하여ㅠㅠㅠㅠ 도움 주시면 감사하겠습니다

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.
모듈과 함께 올려드린 예제는 같은 상황에서 제대로 동작하는 것을 확인하였습니다.
하지만, 말씀하시는 개발환경이 예제와는 차이가 있어 이슈를 재현하는데 어려움이 있습니다.
프로젝트를 아임포트 기술지원 메일주소(support@iamport.kr)로 보내주시면 디버깅하는데 수월할 것 같습니다.
감사합니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.

설명해주신 개발환경을 고려해볼때,
결제를 진행하는 바깥 웹뷰에서 외부 앱 이동을 위한 코드를 직접 작성하셔야 합니다.
아임포트 RN모듈은 이와 같은 코드가 작성되어 있는데,
이를 또 다른 웹뷰가 감싸고 있는 상황이기 때문에 외부 앱으로 이동하지 않는 것으로 추측됩니다.
따라서 바깥 웹뷰에서 RN모듈이 아닌, 아임포트 sdk의 IMP.request_pay를 호출해 결제하는 것을 권장합니다.

참고로 아임포트 RN모듈은(안드로이드의 경우), PG사와 통신과 및 외부 앱 이동을 위해 [네이티브 컴포넌트](https://facebook.github.io/react-native/docs/native-components-android)로 구성되어 있습니다.
네이티브 컴포넌트에서 웹뷰에 웹뷰 클라이언트를 지정하고,
shouldOverrideUrlLoading 메소드에서 url 파라미터에 따라 결제 완료/실패 혹은 외부 앱으로의 이동 등을 판단 및 결정합니다.

결제를 진행하는 웹뷰에 PG사와 통신 및 외부 앱 이동을 위해 위와 같은 네이티브 코드를 작성하시고
IMP.reuqest_pay를 호출해 결제를 진행하시길 바랍니다.

**Comment by Army-92** [comment]
> 안녕하세요 아임포트입니다.
> 
> 설명해주신 개발환경에서는, 결제를 진행하는 바깥 웹뷰에서 외부 앱 이동을 위한 코드를 직접 작성하셔야 합니다.
> 아임포트 RN모듈은 이와 같은 코드가 작성되어 있지만, 이를 또 다른 웹뷰가 감싸고 있는 상황이기 때문에
> 외부 앱으로 이동하지 않는 것으로 추측됩니다.
> 따라서 웹뷰에서는 RN모듈이 아닌,
> 아임포트 sdk(IMP.request_pay)를 호출해 결제하는 것을 권장합니다.
> 
> 참고로 아임포트 RN모듈은(안드로이드의 경우), PG사와 통신 및 외부 앱 이동을 위해 [네이티브 컴포넌트](https://facebook.github.io/react-native/docs/native-components-android)로 구성되어 있습니다.
> 네이티브 컴포넌트에서 웹뷰에 웹뷰 클라이언트를 지정하고,
> shouldOverrideUrlLoading 메소드에서 url 파라미터에 따라 결제 완료/실패 혹은 외부 앱으로의 이동 등을 판단 및 결정합니다.
> 
> 결제를 진행하는 웹뷰에 PG사와 통신 및 외부 앱 이동을 위해 위와 같은 네이티브 코드를 작성하시고
> IMP.reuqest_pay를 호출해 결제를 진행하시길 바랍니다.
> 
> 그래도 이슈가 해결되지 않으면,
> 아임포트 기술지원메일([support@iamport.kr](mailto:support@iamport.kr))로 프로젝트를 보내주세요.
> 
> 감사합니다.

해당 프로젝트 메일로 첨부해서 보내드렸습니다 확인 부탁드립니다~ 도움 주셔서 감사합니다~!

**Comment by SoleeChoi** [comment]
확인하였습니다. 디버깅 후 안내해드리겠습니다.

**Comment by Army-92** [comment]
안녕하세요 최근에  '[iamport/iamport-react-native] 웹뷰에서 아임포트 실행시 외부 앱이 열리지 않습니다 '
라는 제목으로
프로젝트를 발신 하였는데 디버깅 진행 후 다시 보내 주신다고 하였는데 진행과정에 대해 문의 드릴려고 메일드립니다
전부가 아니더라도 방향만 잡아주시면 여기서 한번 해보겠습니다

도움 너무나 감사드립니다
=====

2019년 2월 25일 (월) 오후 4:50, Solee Choi <notifications@github.com>님이 작성:

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.
보내주신 프로젝트 돌려보고 소스를 살펴보니 외부 앱 이동을 위한 코드 작성이 필요해보입니다.
방향을 잡아달라고 하셨는데, 제가 이미 안내해드린 바로 충분하셨을거라 생각합니다.
하지만 보다 자세한 설명을 위해 몇가지 설명을 덧붙이겠습니다.

1. IOS
- [아임포트 RN 모듈 설정하기](https://github.com/iamport/iamport-react-native/blob/master/SETTING.md)를 참고하시고 외부 앱 이동을 위한 기본 설정을 해주세요.
- [아임포트 RN 모듈 코드](https://github.com/iamport/iamport-react-native/blob/master/src/components/Payment/index.ios.js)를 참고하시어 필요한 코드를 작성해주세요. 주석을 잘 달아 놓았으니 이해하시기 한결 수월하실 겁니다.
- 여기서 필요한 부분이란, `onNavigationStateChange`와 `onError`함수입니다. 현재 띄우고 계신 웹뷰에 해당 함수에 대한 처리를 해주세요.
- [onNavigationStateChange](https://facebook.github.io/react-native/docs/webview#onnavigationstatechange) 함수는 필요한 앱이 설치되지 않았을 경우를 대비해 마켓URL를 설정하는 것이고, [onError](https://facebook.github.io/react-native/docs/webview#onerror) 함수는 `onNavigationStateChange` 함수에서 설정한 마켓URL 값을 참고해 앱 스토어로 이동하기 위해 사용됩니다.
- 참고로, 사용하고 계신 이니시스는 모바일 결제시 콜백을 지원하지 않기 때문에 IMP.request_pay의 두번째 파라미터가 결제 후 동작하지 않습니다. 결제 후 동작을 위해서 [m_redirect_url](https://docs.iamport.kr/implementation/payment#mobile-web)을 사용하시기 바랍니다.

2. Android
- 안드로이드는 따로 [네이티브 UI 컴포넌트](https://facebook.github.io/react-native/docs/native-components-android)를 만들어야 합니다.
- [다음 코드](https://github.com/iamport/iamport-react-native/blob/master/android/src/main/java/com/iamport/IamportWebView.java)를 참고하시어 웹뷰를 만들고 필요한 설정을 해주세요.
- [ViewManager](https://github.com/iamport/iamport-react-native/blob/master/android/src/main/java/com/iamport/IamportViewManager.java)에서 `createViewInstance` 메소드를 통해 웹뷰와 웹 클라이언트를 지정합니다.
- [WebViewClient](https://github.com/iamport/iamport-react-native/blob/master/android/src/main/java/com/iamport/webviewclient/IamportWebViewClient.java)에서 `shouldOverrideUrlLoading` 메소드를 통해 외부 앱 실행을 실행합니다.

아임포트 RN 모듈은 RN에서 IMP.request_pay를 호출하기 위해 작성된 코드입니다. 따라서 javascript를 inject하고 postMessage를 주고받으며 콜백을 지원하기 위한 코드 등이 작성되어 있습니다. 또한 아임포트가 지원하는 모든 PG사에 대응하기 위한 코드도 작성되어 있습니다. 사용자께서는 이를 제외하고 위 설명을 토대로 필요한 부분만 참고하시면 됩니다.

감사합니다.

**Comment by Army-92** [comment]
답변 감사합니다 말씀해주신 방향으로 구현해보겠습니다😀
오늘도 좋은 하루 보내세요~!!!

2019년 3월 5일 (화) 오전 11:00, Solee Choi <notifications@github.com>님이 작성:

**Comment by Army-92** [comment]
안녕하세요 예전에 웹뷰안에 웹뷰로 아엠포트 외부 앱 연동에 대해서 여쭈어 봤는데요 번거롭게 해드려서 죄송합니다ㅠㅠ
저번에 말씀해주신 방향으로 구현 중에 막혀서 이렇게 메일을 보냅니다.
제가 이해한 방향으로는 안드로이드에서 네이티브 UI WebView 컴포넌트를 만들고 그것을 react native 에서 호출해서
쓰는것으로 받아들였는데요


   - 안드로이드는 따로 네이티브 UI 컴포넌트
   <https://facebook.github.io/react-native/docs/native-components-android>를
   만들어야 합니다.
   - 다음 코드
   <https://github.com/iamport/iamport-react-native/blob/master/android/src/main/java/com/iamport/IamportWebView.java>를
   참고하시어 웹뷰를 만들고 필요한 설정을 해주세요.
   - ViewManager
   <https://github.com/iamport/iamport-react-native/blob/master/android/src/main/java/com/iamport/IamportViewManager.java>에서
   createViewInstance 메소드를 통해 웹뷰와 웹 클라이언트를 지정합니다.
   - WebViewClient
   <https://github.com/iamport/iamport-react-native/blob/master/android/src/main/java/com/iamport/webviewclient/IamportWebViewClient.java>에서
   shouldOverrideUrlLoading 메소드를 통해 외부 앱 실행을 실행합니다.


답변 중에 웹 클라이언트를 따로 지정하라는 말씀이 이해가 안가서... 웹 클라이언트는 구체적으로 어떤 것을 이야기 하는 것인가요?
이를 지정 하라는 것이 무엇인지 몰라 그냥 예제 파일에 있는 것을 그대로 사용하였는데 ReferenceError:
ReferenceError:Can't find variable: IamportWebView 라고 오류 로그가 뜨네요

리엑트 네이티브를 시작 한지 얼마 안되서... 개념이 부족해서 죄송합니다
*현재까지 구현한 코드 같이 첨부합니다 (webview 코드 경로는 /src/Webview/index.js에 위치해 있습니다.)*

죄송하고 감사합니다 😂
 bagstation-react-native.zip
<https://drive.google.com/file/d/1kPGmnGoRQWOYettZtZuZu5oEY7H9aTbk/view?usp=drive_web>

2019년 3월 5일 (화) 오전 11:32, Solee Choi <notifications@github.com>님이 작성:

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.

귀하와 비슷한 환경에서 아임포트 모듈을 연동하고자 하는 문의가 종종 있어
보다 쉽게 연동할 수 있도록 예제 프로젝트(`exampleForWebView`)와 메뉴얼을 따로 만들었습니다.
해당 내용은 https://github.com/iamport/iamport-react-native/blob/master/exampleForWebView/README.md 에서 확인 가능합니다.

감사합니다.
