### ISSUE TITLE
예제프로그램들이 돌아가나요?

### ISSUE THREAD

**Issue by bryce0516** [iamport/iamport-react-native#113]
podfile도없고 프로젝트를 어떻게 돌려야되나요? npm install 밖에 해줄게 없는거 같은데 ios에서는 못돌려보나요?

**Comment by rxYoungho** [comment]
저도 ios로 시도중이긴 한데 README대로 해도 안되네요. 혹시 무언가 놓친게 있으면 추가 부탁드립니다.
