### ISSUE TITLE
package.json 파일 내부에 react-native-gesture-handler 추가가 안된 사항.

### ISSUE THREAD

**Issue by sangl83** [iamport/iamport-react-native#12]
안녕하세요. 샘플 프로젝트를 구동하려고 하다보니
문제점이 있어 글 남깁니다.

package.json 에서는 react-native-gesture-handler 의 dependencies 에 추가가 안되어 있는데

안드로이드에 settings.gradle 파일 안에는

include ':react-native-gesture-handler'
project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-gesture-handler/android')

이렇게 되어 있습니다.

그래서 yarn add react-native-gesture-handler 을 하여 추가하여도 제대로 컴파일이 되지 않습니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.

이슈 확인 되셨으며 빠른 시일내에 답변 드리도록 하겠습니다.

감사합니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.

아임포트 모듈 내부 샘플 프로젝트를 새로 clone 받아 안드로이드에서 실행해본 결과 정상적으로 동작합니다.
실행 과정은 아래와 같습니다.

```
$ git clone https://github.com/iamport/iamport-react-native.git // 아임포트 모듈을 clone 받습니다.
$ cd ./iamport-react-native/example                                              // 아임포트 모듈 내부 샘플 프로젝트로 이동합니다.
$ npm install                                                                                     // 샘플 프로젝트에서 필요한 모듈을 설치합니다. 이 과정에서 react-native-gesture-handler 모듈도 함께 설치됩니다.
$ react-native run-android                                                             // 안드로이드 기기를 연결하거나 AVD를 실행해 앱을 설치합니다.
```

물론 샘플 프로젝트 내부 package.json 파일의 dependencies에 `react-native-gesture-handler` 모듈이 포함되어 있지 않지만
샘플 프로젝트에서 npm install을 하면 react-native-gesture-handler 모듈도 함께 설치됩니다.
그 이유는 dependencies에 속한 다른 모듈이 해당 모듈을 dependency로 사용하고 있을 가능성이 있습니다.

말씀하신 `example/android/settings.gradle`에서 해당 모듈을 참조할때 경로는 `node_modules/react-native-gesture-handler/android`입니다. 때문에 node_modules에 `react-native-gesture-handler` 모듈이 포함되어 있는 경우 정상적으로 앱이 설치되고 실행됩니다.

앞서 소개해드린 방법대로 다시 한 번 실행해주세요.
그래도 되지 않을 경우 자세한 상황(어떤 명령어를 실행시 어떤 에러메시지가 뜨는지 등)과 함께 프로젝트를 아임포트 기술지원 메일(support@iamport.kr)로 보내주시면 디버깅 해 보겠습니다.

감사합니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.

아임포트 기술지원 메일로 보내주신 에러 상황을 토대로 분석해 본 결과
**아임포트 모듈 내부 샘플프로젝트의 react-native 버전문제**인 것으로 확인됩니다.

사용자께서는 윈도우 환경에서 테스트 하고 계신데
**윈도우 환경에서는 react-native 0.56.0 버전이 제대로 동작하지 않습니다.**
해당 내용은 react-native 이슈에도 등록되어 있어 아래 링크를 통해 확인 가능합니다.
[https://github.com/facebook/react-native/issues/20331](https://github.com/facebook/react-native/issues/20331)

윈도우 환경에서 테스트를 위해 샘플 프로젝트의 react-native 버전을 올린 후 다시 npm install을 해보시기 바랍니다.
향후 아임포트 모듈 업데이트시 샘플 프로젝트의 react-native 버전을 올리도록 하겠습니다.

감사합니다.
