### ISSUE TITLE
2.0.0 디펜던시 에러

### ISSUE THREAD

**Issue by pjc0247** [iamport/iamport-react-native#130]
```
  "dependencies": {
    "iamport-react-native": "^2.0.0-rc.0",
    "react": "17.0.1",
    "react-native": "0.64.2",
    "react-native-webview": "^11.6.6"
  },
```

위와 같은 디펜던시만 가지고 실행하면 `query-string` 을 찾을 수 없다는 에러가 나옵니다.

**Comment by anymate98** [comment]
그래서 peerDependency에 `query-string`을 넣었으니 직접 설치하면 사용하실 수 있습니다.

**Comment by pjc0247** [comment]
https://github.com/react-navigation/react-navigation/blob/main/packages/core/package.json#L41
처럼 dependencies에 넣어 별도 설치 없이 사용하게 해주시는건 어떨까요?

대부분 경우에 react-navigation없이 작업하는 경우가 잘 없어서, 저도 빈 프로젝트에서 에러 재현하다가 발견했습니다.

**Comment by anymate98** [comment]
혹시 npm 버전이 어떻게 되시나요?

**Comment by pjc0247** [comment]
@anymate98 

답변이 늦어 죄송합니다.
yarn 입니다.
```
C:\Users\pjc>yarn --version
1.22.5
```

**Comment by anymate98** [comment]
query-string을 peerDependency로 설정한 이유는 기존에 사용하던 패키지와 별개로 강제 설치가 된다면 충돌이 일어나는 이슈가 예전에 발견되었기 때문입니다. npm의 경우 7버전부터는 peerDependency를 자동으로 설치할 수 있게 바뀌었으므로 사용자별로 작동이 다를 수 있겠고, yarn의 경우에는 그 기능이 없기 때문에 warning 메시지를 참고 후 직접 설치하는 과정이 필요하겠습니다.

**Comment by pjc0247** [comment]
@anymate98 네 알겠습니다. 이슈는 닫도록 하겠습니다.
