### ISSUE TITLE
[다날 서버로부터 받은 응답이 올바르지 않습니다] 에러가 발생합니다.

### ISSUE THREAD

**Issue by skkim-pixel-monster** [iamport/iamport-react-native#133]
아래와 같은 예제 코드대로 적용했습니다 (실제 예제코드를 실행하지는 않음)
개인정보 및 중요정보는 asterisk 처리했습니다.

    const handleCompleted = (response: any) => {
        console.log(response)
    }

    const data = {
        merchant_uid: ***,
        company: '***',
        carrier: 'KT',
        name: '김**',
        phone: '010********',
    };

    return (
        <SafeAreaView style={{ flex: 1, justifyContent: 'center' }}>
            <IMP.Certification
                userCode={'imp***'}
                data={data}
                loading={<FullScreenLoading />}
                callback={handleCompleted}
            />
        </SafeAreaView>
    );

해당코드를 실행시키면, 다음과 같은 에러가 발생합니다. 

`
 LOG  {"error_code": "9010", "error_msg": "다날 서버로부터 받은 응답이 올바르지 않습니다.[인증실패] 잘못된 값이 입력된 필드가 존재합니다. (다날고객센터 1566-3355)", "success": false}
`

중요한 것은 
**android / ios / web 전부 동일한 현상이 발생합니다~**

아임포트 관리자 페이지에서
**시스템설정 > 본인 인증 서비스 > PG사, CPID 까지 입력완료**한 상태입니다.

현재 저희는 pg 는 사용하지 않고, 본인인증 서비스만 신청했습니다. 
처리방법을 알려주실 수 있으신가요?

**Comment by anymate98** [comment]
안녕하세요, 아임포트 기술지원팀입니다.

kt의 동신사 값은 KTF로 써주셔야 합니다.

**Comment by skkim-pixel-monster** [comment]
@anymate98
답변 감사드립니다~

KTF 로 변경했는데도 동일한 에러가 발생하네요 :(

**Comment by skkim-pixel-monster** [comment]
<script type="text/javascript">
        IMP.init('imp***');
        IMP.certification({
            m_redirect_url: "http://localhost:3000/api/certifications",
            popup: false
        }, function (rsp) {
            if (rsp.success) {
                // 인증성공
                console.log('success', rsp)
            } else {
                // 인증취소 또는 인증실패
                console.log('fail', rsp)
            }
        });
    </script>

웹에서는, 이렇게 실행시켜도 
`fail {success: false, error_code: "9010", error_msg: "다날 서버로부터 받은 응답이 올바르지 않습니다.[인증실패] 잘못된 값이 입력된 필드가 존재합니다. (다날고객센터 1566-3355)"}`

이런 에러가 발생합니다~

제가 넣는 값의 문제가 아닌 것 같아서요~

**Comment by anymate98** [comment]
관리자 페이지에서 CPID 뿐만 아니라 CPPWD도 설정을 해주셨는지 확인 가능할까요?

**Comment by skkim-pixel-monster** [comment]
> 관리자 페이지에서 CPID 뿐만 아니라 CPPWD도 설정을 해주셨는지 확인 가능할까요?

다날쪽에 연락하여 확인했습니당~
서비스 정상동작하는 부분도 확인했습니다.

확인 감사드립니다.
