### ISSUE TITLE
정기결제가 되지 않습니다. 

### ISSUE THREAD

**Issue by aborile** [iamport/iamport-react-native#141]
[아임포트 개발자 문서 - 정기결제 연동하기](https://docs.iamport.kr/implementation/subscription)를 참고해서 정기결제 개발을 시도해보고 있었으나, 잘 되지 않습니다. 
다날(카드)과 카카오페이를 사용하고 있습니다. (일반 결제의 경우 두 방식 모두 문제 없이 동작합니다.)

1. 우선, `IMP.request_pay(param, callback)`를 호출하라고 적혀있는데, iamport-react-native에는 이러한 함수가 없고 (일반결제 문서와 비교해서 읽어보았을 때) `IMP.Payment` 컴포넌트를 나타내는거라 생각하고 이를 사용하였습니다. 
2. 문서를 읽어봤을 때, [다날-신용카드 정기결제 연동 가이드](https://github.com/iamport/iamport-manual/blob/master/%EB%B9%84%EC%9D%B8%EC%A6%9D%EA%B2%B0%EC%A0%9C/example/danal-card-request-billing-key.md)와 [카카오페이 정기결제 연동 가이드](https://github.com/iamport/iamport-manual/blob/master/%EB%B9%84%EC%9D%B8%EC%A6%9D%EA%B2%B0%EC%A0%9C/example/kakaopay-request-billing-key.md) 모두 `customer_uid`를 지정해야 빌링키 등록이 진행된다고 적혀있었으므로, `customer_uid`를 지정해주는 것이 중요한 포인트라 생각해서 data에 이를 지정해주었습니다.

위와 같이 생각하고 구현하였는데, 다날의 경우 에러가 발생하고, 카카오페이의 경우 일반 결제가 정상적으로 진행되나 curl로 재결제를 요청하면 '등록되지 않은 사용자입니다.'라는 에러가 뜹니다. 

구현 시에 놓친 정보가 뭐가 있을까요? 가이드대로 잘 따라했다고 생각했는데 되지 않아 어렵네요 😢 
관련된 정보를 하단에 첨부합니다. 

#### 코드 정보
```javascript
<IMP.Payment
    data={{
        pg, // 'danal_tpay' | 'kakaopay'
        pay_method: 'card',
        escrow: false,
        merchant_uid: `mid-${account.id || '00'}-${new Date().getTime()}`,
        customer_uid: `${account.id || '00'}-${new Date().getTime()}`,
        // 하단의 정보는 결제정보/사용자정보가 변수로 들어가 있습니다. 
        name: paymentName,
        amount,
        buyer_name,
        buyer_tel,
        buyer_email,
    }}
    userCode={userCode} // 가맹점 식별코드
    loading={<LoadingIndicator />} // 로딩 컴포넌트
    callback={paymentCallback} // 결제 종료 후 콜백
/>
```

#### 다날(카드)결제 실패 스크린샷
<img src="https://user-images.githubusercontent.com/37267486/134610940-f1bfab60-77c4-4c05-99e7-c466481903aa.png" height="500" />

(data 중 `customer_uid` 만 빼고 동일한 data를 넣으면 일반결제가 정상적으로 진행됩니다.)

#### 카카오페이 결제 후 로그
결제 성공 시 로그
```json
{
   "imp_success": "true",
   "imp_uid": "imp_'MY_IMP_UID'",
   "merchant_uid": "mid-1-'MY_MERCHANT_UID'"
}
```

curl 요청 실패 로그
```json
// curl 요청
curl -H "Content-Type: application/json" -X 
    POST -d '{"customer_uid":"1-'MY_CUSTOMER_UID'", "merchant_uid":"'MY_MERCHANT_UID'", "amount":100, "name": "test"}' 
    -H "Authorization: 'MY_ACCESS_TOKEN'" https://api.iamport.kr/subscribe/payments/again

// error response 
{"code":1,"message":"\ub4f1\ub85d\ub418\uc9c0 \uc54a\uc740 \uad6c\ub9e4\uc790\uc785\ub2c8\ub2e4.","response":null}
```

특히 결제 금액을 0원으로 지정하고 시도해봤을 때 
```json
{
   "success": false,
   "error_code": "ERROR",
   "error_msg": "onetime order should have amount!"
}
```
와 같은 로그가 뜨는 것으로 보아 일반 결제로 인식되는 것 같습니다.

----

개발 스펙은 다음과 같습니다. 
"iamport-react-native": "^2.0.0-rc.0",
"react-native": "0.63.3",

**Comment by anymate98** [comment]
안녕하세요, 아임포트 기술지원팀입니다.

우선 리액트 네이티브 쪽의 문제는 아닌 것으로 보이고요, PG 설정의 문제일 것으로 추정됩니다.
가맹점 식별코드와 함께  support@iamport.kr로 문의주시면 문제의 원인을 더 자세히 알 수 있을 것 같습니다.
