### ISSUE TITLE
로딩페이지에서 넘어가지 않는 증상

### ISSUE THREAD

**Issue by Grapevine42** [iamport/iamport-react-native#15]
react-native-cli: 2.0.1
react-native: 0.59.4

본인인증 모듈을 활용하려고 하는데
postMessage 를 전송하지 못하는지
아임포트 로고가 떠있는 로딩 페이지에서 다음페이지로 넘어가질 않습니다

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.

현재 테스트 중이신 환경과 파라미터 정보를 알려주시면 보다 안내가 수월할 것 같습니다.

- 환경: IOS/안드로이드
- 파라미터: <IMP.Certification />에 전달하고 계시는 파라미터로, userCode(가맹점 식별코드), data(본인인증 데이터) 등

감사합니다.

**Comment by Grapevine42** [comment]
환경 안드로이드에서 진행중이며

     userCode={'개인가맹점코드'} // 가맹점 식별코드
                data={data} // 본인인증 데이터

식별코드만 제공받은 코드를 넣으며
data 는 예제소스 그대로 사용중입니다.



        const data = {
            merchant_uid: `mid_${new Date().getTime()}`,
            min_age: '',
        };

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.

휴대폰 본인인증은 PG사와 계약을 맺어야 테스트 해보실 수 있기 때문에,
정확한 파악을 위해 가맹점 식별코드를 알려주셔야 합니다.

깃헙이 오픈된 공간이라 가맹점 식별코드를 알려주시기 부담스러우시다면,
카카오톡 옐로우아이디로 전달 부탁드립니다.

감사합니다.

**Comment by Grapevine42** [comment]
넵 감사합니다

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.

휴대폰 본인인증서비스는 앞서 설명드린 바와 같이
PG사와 계약을 맺어야 테스트 및 상용 모드 사용이 가능합니다.
자세한 사항은 메일로 안내드리겠습니다.

감사합니다.
