### ISSUE TITLE
기본 결제모듈 호출 시 간편결제 콜백이 제대로 동작하지 않습니다.

### ISSUE THREAD

**Issue by mckim0408** [iamport/iamport-react-native#152]
## 오류 항목
현재 나이스페이 pg를 사용중이고, 기본 결제모듈 호출 방식을 수행하고자 합니다.
결제 방식은 카드 결제만 사용할 예정인데, 모듈에서 기본적으로 간편결제 항목들이 표시됩니다.

![결제창](https://user-images.githubusercontent.com/50772382/149073031-8a3e9153-bfeb-48e1-8f07-931e3fa228ea.png)

이때 간편결제를 진행할 경우 항상 다음과 같은 콜백이 넘어옵니다.
`{"error_msg": "에러코드 : ", "imp_success": "false", "imp_uid": "imp_************", "merchant_uid": "asdfasd5"}`

위와 같이 에러 코드가 제대로 나오지 않아 문제를 파악하기 어렵습니다.

## 테스트 환경
Android

AndroidMenifest에 다음과 같이 intent-filter를 추가해주었습니다.
(example에서 안드로이드는 scheme을 지정하지 않는다고 되어있는데 혹시 몰라서 scheme을 넣었을 때와 제거했을 때 두 케이스를 모두 시도해봤지만 해결되지 않았습니다.)
```xml
<intent-filter>
     <action android:name="android.intent.action.VIEW" />
     <category android:name="android.intent.category.DEFAULT" />
     <category android:name="android.intent.category.BROWSABLE" />
     <data android:scheme="iamport_callback_scheme" />
</intent-filter>
```

## 모듈 버전
"iamport-react-native": "^2.0.0-rc.0",
"react": "17.0.1",
"react-native": "0.64.1",

## Source
```typescript
import Config from 'react-native-config';
import IMP from 'iamport-react-native';

const IMPTest = () => {
   const callback = (response:any) => {
      console.log(response);
   }

   return (
      <IMP.Payment
         userCode={Config.IAMPORT_ID}
         callback={callback}
         loading={<ActivityIndicator size="large" color={theme.colors.primary} />}
         data={{
            pg: 'nice',
            escrow: false,
            name: 'test',
            buyer_name: 'test',
            buyer_email: 'test@tewst.com',
            pay_method: 'card', // card | trans | tosspay
            merchant_uid: 'asdfasd5',
            amount: 1000,
            buyer_tel: '01012344321',
            app_scheme: 'iamport_callback_scheme',
            digital: true
         }}
      />
   );
}
```

**Comment by anymate98** [comment]
안녕하세요, 아임포트 기술지원팀입니다.

현재 나이스 결제창 ui 문제가 있어보이는데 data 파리미터에 niceMobileV2: true 를 넣어보시겠어요?

**Comment by mckim0408** [comment]
타입스크립트를 사용중이라 data파라미터에 @ts-ignore 와 함께 추가하니 정상적인 결제 창이 뜨는 것 같습니다. 감사합니다.
