### ISSUE TITLE
KG이니시스 휴대폰 소액 결제 창 문의 드립니다.

### ISSUE THREAD

**Issue by boodong-rn** [iamport/iamport-react-native#161]
PG사는 `KG이니시스`입니다.

https://github.com/iamport/iamport-manual/blob/master/%EC%9D%B8%EC%A6%9D%EA%B2%B0%EC%A0%9C/sample/inicis.md

카드 결제 창은 잘 뜨고 있으며 휴대폰 소액 결제 구현을 위해 상위 매뉴얼을 보면서 구현 중에 있습니다.
휴대폰 결제를 위해 `pay_method`를 `'phone'`로 바꾸면 화면이 제대로 나타나지 않습니다.

휴대폰 소액 결제를 위해 KG 이니시스 측으로 부터 인증 절차가 더 필요해서 그런 걸까요?
화면은 제대로 나오고 있지 않지만 관련 response가 따로 없어서 상태를 정확히 판단할 수 없습니다.

**Comment by boodong-rn** [comment]
> 제대로 나타나지 않는 화면 사진 첨부 부탁드립니다. 또한 결제창 호출하실 때 사용하신 파라미터도 알려주시면 감사하곘습니다.

## 화면 사진
![image](https://user-images.githubusercontent.com/95212382/150742214-a38a13b7-2cd6-4955-82ff-a1679296901a.png)

```jsx
  const [isModalOpen, setIsModalOpen] = useState(false)

  const data = {
    pg: 'html5_inicis',
    pay_method: 'phone',
    name: '100코인',
    merchant_uid: new Date(),
    amount: '100',
    buyer_name: '홍길동',
    buyer_tel: '01012345678',
    buyer_email: 'example@naver.com',
    buyer_addr: '서울시 강남구 신사동 661-16',
    buyer_postcode: '06018',
    app_scheme: 'boodongboodong',
  };

return (
  <Modal
      isVisible={isModalOpen}
      onBackdropPress={() => setIsModalOpen(false)}>
      <SafeContainer>
          <IMP.Payment
            userCode={'imp47840029'} // 가맹점 식별코드
            loading={<BasicLoading />} // 로딩 컴포넌트
            data={paymentData} // 결제 데이터
            callback={callback} // 결제 종료 후 콜백
        />
      </SafeContainer>
  </Modal>
)

```

모달 안에서 구현하고 있습니다. 모달 여는 결제 버튼을 따로 적진 않았지만 버튼을 누르면 isModalOpen이 true가 됩니다.
SafeContainer는 SafeArea 벗어나지 않게 하기 위해 SafeAreaView에 absoluteFill 적용해둔 컴포넌트 입니다.

**Comment by boodong-rn** [comment]
혹시 휴대폰 결제 계약이 체결 되어야만 화면이 불러와지는 걸까요? `imp47840029`로 확인 한 번 해주실 수 있나요? 아니면 제가 따로 확인할 수 있는 방법이 있을까요?

**Comment by anymate98** [comment]
현재 테스트 모드로 설정되어 있어 문제없으실 겁니다.
휴대폰 소액결제의 경우 digital값이 빠지면 결제가 불가능하므로 해당 파라미터 한번 채워서 결제해보시겠어요?

**Comment by boodong-rn** [comment]
`data` prop에 digital을 빈 스트링으로 넣어 주니 됐습니다! 감사합니다!
혹시 여기 digital에는 어떤 값이 들어가야 하는지 알 수 있을까요?
문서에서 찾아 봤지만 제가 못 찾는 건지 안보입니다..

**Comment by anymate98** [comment]
https://docs.iamport.kr/sdk/javascript-sdk
상품이 실물인지 디지털 컨텐츠인지 명시해주는 파라미터입니다.

**Comment by boodong-rn** [comment]
그렇군요! 문서를 좀 더 꼼꼼히 봐야 겠군요! 도와 주셔서 감사합니다!
