### ISSUE TITLE
type 지정 문제

### ISSUE THREAD

**Issue by swkang0513** [iamport/iamport-react-native#162]
2.0.0-rc.1 버전으로 업그레이드 이후 기존의 타입 지정을 위해 import했던 부분들을 vscode가 찾지 못하는 문제가 발생했습니다.

import IMP, { CallbackRsp, PaymentData } from 'iamport-react-native';

위 import문 처럼 CallbackRsp와 PaymentData를 import할 시 has no exported member 오류가 생성됩니다.

@types/iamport-react-native 패키지도 업데이트해주실 수 있으실까요?

**Comment by anymate98** [comment]
@types/iamport-react-native는 저희가 만든 것이 아닙니다.
또한 최근 버전들은 type을 자동으로 생성해서 같이 배포합니다.
해당 패키지를 제거하고 이용해주시면 되겠습니다.
