### ISSUE TITLE
iOS에서 결제시 실패

### ISSUE THREAD

**Issue by lizhming** [iamport/iamport-react-native#166]
"iamport-react-native": "^2.0.0-rc.2",
"react-native-webview": "^11.6.4",

안녕하세요
안드로이드에서는 오류 없이 결제페이지 연동되는데 iOS에서는 결제시 로딩페이지 표시되다가 오류메시지 없이 결제실패합니다.
{"imp_uid": "imp_553889424290", "merchant_uid": "111", "success": false}

**Comment by anymate98** [comment]
실패 상황에 대한 정보를 더 제공부탁드립니다.
어떤 pg사, 어떤 수단으로 결제했는지,
결제 프로세스 중 어디에서 막히는지 더 자세한 셜명이 필요합니다.

**Comment by lizhming** [comment]
iOS에서 useAgent에 커스텀 추가해서 결제할수 없는 기기라는 오류가 나오던것 같습니다.
해당 부분 제거후 결제가 됩니다.
감사합니다.
