### ISSUE TITLE
expo managed 예제 테스트중 질문드립니다.

### ISSUE THREAD

**Issue by baesumin** [iamport/iamport-react-native#179]
안녕하세요.
현재 예제 테스트로 결제 테스트는 성공한 상황입니다.
추가적으로 궁금한 점이 아임포트 관리자페이지에서 결제 내역을 확인해보려면 저의 가맹점 식별코드를 사용하는걸로 이해했는데 어디부분에 적용하면 되는지 알 수 있을까요? 시도해본건 utils.js에 getUserCode 함수 return 부분을 저의 가맹점 식별코드로 바꿔봤더니 결제를 시도하면 등록되지 않았다고 오류가 떠서 질문드립니다.
감사합니다.

**Comment by baesumin** [comment]
답변해주셔서 감사합니다. 관리자페이지에서 내역->결제내역 탭에 있는건 테스트 용도로는 활용할 수 없고 실제로 pg사 및 결제 수단이 등록되어야 결제내역 탭부분을 쓸 수 있는걸까요? 혹시 테스트 용도로도 결제내역 탭을 확인해볼 수 있다면 방법을 알려주시면 감사하겠습니다!

**Comment by anymate98** [comment]
결제 연동 메뉴에 있는 테스트 연동 및 실 연동에 pg가 하나라도 등록이 되어있는지를 확인하고자 하는 것이었습니다.

**Comment by baesumin** [comment]
네, 현재 '테스트 연동'에 '신용카드-나이스페이먼츠'로 연결되어 있어서 테스트할때에도 나이스페이먼츠로 결제를 진행해보았는데요. 내역-결제내역쪽에는 따로 내역이 뜨지는 않았습니다.(나이스페이먼츠로 2건 결제 진행 후 저녁 12시전 취소되는 것은 확인했습니다) 
테스트 연동에 나이스페이먼츠를 등록했는데 PG상점아이디(MID), KEY, 결제취소 비밀번호는 따로 코드쪽에 적어두지 않았는데 혹시 이것 때문일까요?
퇴근시간이실 것 같은데 내일 답변해주셔도 됩니다! 감사합니다.

**Comment by anymate98** [comment]
안녕하세요. 해당 키값들이 일단 설정이 되어있다면 결제에는 문제가 없을 것 같은데 실제 예제 실행 도중 발생하는 에러 화면을 보여주시면 문제 해결에 도움이 될 것 같습니다.

**Comment by baesumin** [comment]
아 넵, 저번에 말씀주신것처럼 결제 수단 등록하니 정상 결제 진행됩니다! 감사합니다.
