### ISSUE TITLE
[ios]duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by claudepark** [iamport/iamport-react-native#18]
ios 네이티브 빌드시 
duplicate symbols for architecture arm64
이런 에러가 발생합니다.

react-native link iamport-react-native
react-native link react-native-webview

iamport-react-native 내부의 react-native-webview 와 충돌이 나서 그런거 같은데
어떻게 해야될까요?

**Comment by zheldRnaskan** [comment]
xcode에서 프로젝트에 추가된 iamport-react-native 의 하위에 있는 react-native-webview 를 삭제하니 되었던 것 같습니다

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.

등록해주신 이슈는 말씀하신대로 iamport-react-native가 react-native-webview를 링크하고 있었기 때문에 발생한 문제였습니다. 해당 내용은 수정해 v1.1.3-rc에 반영하였습니다. 감사합니다.

감사합니다.
