### ISSUE TITLE
마크다운 문서의 링크에 오류가 있습니다. 

### ISSUE THREAD

**Issue by ingyulee-genesislab** [iamport/iamport-react-native#180]
대상 URL: https://github.com/iamport/iamport-react-native/blob/main/manuals/EXAMPLE.md?plain=1#L81

`data` 객체의 설명을 보기 위해 표의 Description에 있는 **자세히 보기** 를 눌렀으나 없는 페이지로 이동됩니다.

**Comment by anymate98** [comment]
피드백 감사합니다. 추후 수정할 수 있도록 하겠습니다.

**Comment by hyp3rflow** [comment]
https://github.com/iamport/iamport-react-native/issues/192 에서 관리하도록 하겠습니다. 감사합니다 🚀
