### ISSUE TITLE
콜백 함수관련 문의사항입니다.

### ISSUE THREAD

**Issue by JamesSleep** [iamport/iamport-react-native#182]
현재 저희앱의 코드를 다 가져오기에는 양이 많아서 약식으로 작성했습니다.
예약관련코드입니다.

```
...
import IMP, {IMPData} from 'iamport-react-native';
...

const [showIamport, setShowIamport] = useState(false);

const data: IMPData.PaymentData = {
  escrow: false,
  pg: 'uplus',
  pay_method: 'card',
  name: `${dosa.name} 상담 30분`,
  merchant_uid: `mid_${new Date().getTime()}`,
  amount: totalPrice - Number(pointText),
  buyer_name: UserStore.user.name,
  buyer_tel: phone,
  buyer_email: UserStore.user.email,
  buyer_addr: '',
  buyer_postcode: '',
  app_scheme: 'iamport',
  display: {
    card_quota: [2, 3],
  },
};

const onPayments = async response => {
    if (response.error_msg) {
      setShowIamport(false);
      showToast(response.error_msg, 'danger', toast);
      return;
    }

    // 결제 성공 후 회사서버에 예약 데이터 전송
}

return (
	...
	{showIamport && (
	<Modal onRequestClose={() => setShowIamport(false)}>
	    <SafeAreaView>
	      <View style={{width: '100%', height: '100%'}}>
	        <IMP.Payment
	          userCode="imp74972766"
	          loading={<Loading />}
	          data={{...data}}
	          callback={onPayments}
	        />
	      </View>
	    </SafeAreaView>
	  </Modal>
	)}

	...
)
```

사용자의 화면에서 어떤 오류가 일어났는지 정확한 판단은 힘들지만 결제성공 이후 callback 함수를 실행하지 못하는 경우가 종종 발생하는것 같습니다. 

결제만 성공하고 예약정보를 저희서버로 보내지 못하는 경우가 발생해 저희가 결제 취소를 해드리고 사용자가 다시 결제했을때 잘넘어가긴했습니다. 

react native에 대한 로그를 아직 저장못하고 있어 서버로그만 확인했을때는 저희 서버에 결제성공건에 대한 request요청 기록이 없었습니다.

아임포트 공식문서에서 모바일웹에서 redirection url이 없으면 토스페이먼츠가 callback 함수를 못받는다고하는데 혹시 이 문제 때문에 이런 이슈가 발생하는걸까요?

회사 개발팀에서는 카드사별로 다 결제테스트를 해보았지만 문제는 없었습니다. 릴리즈된 앱에서 간혹 이슈가 발생중입니다.

**Comment by anymate98** [comment]
앱에서 결제 후 정확히 어떤 일이 발생하는지 모르겠으나 결제 완료가 되고 사용자가 바로 앱을 끄거나 다른 페이지로 넘어가는 등의 행동을 해서 작업이 취소되었을 가능성이 있어보입니다.
코드상의 콜백 함수는 웹뷰 안에서 실행하는 것이 아니므로 결제가 정상적으로 일어난 경우 토스페이먼츠가 콜백함수를 받지 못하는 것과는 크게 관련이 없을 것 같습니다.

**Comment by JamesSleep** [comment]
@anymate98 
빠른 피드백 감사합니다!

**Comment by onionkim** [comment]
저도 이슈 열어주신 분과 동일한 문제가 생기는데 결제 성공 이후 콜백함수 타기 전까지 과정을 트래킹할 수 있는 방법이 없을까요? 혹은 해당 문제를 방지할 수 있는 방법이 없을까요? 도움주시면 감사하겠습니다!
아임포트 대시보드에서는 결제내역 확인되나, 저희 서버에는 반영되지 않는 사례가 간혹가다, 하지만 지속적으로 발생하고 있습니다.
오류 로그 등을 확인할 길이 없어 정확하지는 않지만,
콜백함수에서 서버로 데이터를 전송해주고 이후 200 status를 받고  앱 내 결제완료 창으로 보내는데 콜백 자체를 타지 않는 것 같습니다.

**Comment by onionkim** [comment]
@JamesSleep 
저도 이슈 열어주신 분과 동일한 문제가 생기는데 결제 성공 이후 콜백함수 타기 전까지 과정을 트래킹할 수 있는 방법이 없을까요? 혹은 해당 문제를 방지할 수 있는 방법이 없을까요? 도움주시면 감사하겠습니다!
아임포트 대시보드에서는 결제내역 확인되나, 저희 서버에는 반영되지 않는 사례가 간혹가다, 하지만 지속적으로 발생하고 있습니다.
오류 로그 등을 확인할 길이 없어 정확하지는 않지만,
콜백함수에서 서버로 데이터를 전송해주고 이후 200 status를 받고  앱 내 결제완료 창으로 보내는데 콜백 자체를 타지 않는 것 같습니다.

**Comment by anymate98** [comment]
@onionkim
결제 성공 혹은 실패를 탐지하는데 콜백함수는 사실 권장되는 수단이 아닙니다.
https://portone.gitbook.io/docs/auth/guide/4./redirect
가이드에 설명되어 있듯이 웹훅을 사용하시면 보다 정확한 결제 처리를 하실 수 있습니다.

**Comment by onionkim** [comment]
@anymate98 
조언 감사드립니다! 결제완료 이후 콜백 함수 사용시에는 실행에 대한 순서가 보장되지 않나보네요!
말씀주신대로 웹훅을 적용해 보겠습니다! 감사합니다!

**Comment by onionkim** [comment]
@anymate98 
실례지만 한 가지 더 여쭈어보고 싶습니다! 
1. 관리자 콘솔에서 웹훅 설정을 통해 로컬에서 테스트까지는 마쳤는데, 결제완료 이후 웹훅의 POST 요청 이벤트 실행까지의 텀은 얼마나 되는지 궁금합니다!
2.  웹훅을 통해 결제를 다시 한 번 확인 할 수 있었지만, 앱 클라이언트에서 콜백함수를 사용하는 대신 웹훅을 사용하여 그 결과를 바탕으로 결제완료 이후 로직을 실행하게 할 수는 없을까요?  
- 그렇게 할 수 없다면 웹훅을 사용해도 앱에서 콜백이 실행되지 않을경우 정상적으로 결제완료 화면으로 넘어가지 못하는 문제는 동일할 것 같습니다.
- 혹시 웹훅 설정에 대해 잘못 이해한 부분이 있다면 조언을 받아볼 수 있을까요? 또는 이 라이브러리를 통해 앱에서 콜백대신 웹훅 요청 결과를 기다려 처리하는 로직 예제나 가이드가 있을까요?
감사합니다!
현재 앱 내 결제창 구현 코드 구성입니다.
``` js
        <IMP.Payment
          userCode={'가맹점 식별코드'}
          data={data} // 결제 데이터
          callback={this.callback} // 결제 종료 후 콜백
        />
 ```

**Comment by anymate98** [comment]
@onionkim 
https://portone.gitbook.io/docs/tip/confirm-process
