### ISSUE TITLE
엑스포 빌드 에러

### ISSUE THREAD

**Issue by omnmala** [iamport/iamport-react-native#188]
expo version: 47.0.0

Expo Go에서는 결제 및 테스트 진행이 잘 되었습니다.
빌드를 하니 다음과 같은 에러가 발생합니다.
엑스포 예제 프로젝트를 빌드해도 동일한 에러가 발생합니다.

코틀린 버전 문제인 것 같은데 확인부탁드립니다.

========================================================================
[stderr] FAILURE: Build completed with 2 failures.
[stderr] 1: Task failed with an exception.
[stderr] -----------
[stderr] * What went wrong:
[stderr] Execution failed for task ':iamport-react-native:compileReleaseKotlin'.
[stderr] > Compilation error. See log for more details
[stderr] * Try:
[stderr] > Run with --stacktrace option to get the stack trace.
[stderr] > Run with --info or --debug option to get more log output.
[stderr] > Run with --scan to get full insights.
[stderr] ==============================================================================
[stderr] 2: Task failed with an exception.
[stderr] -----------
[stderr] * What went wrong:
[stderr] java.lang.StackOverflowError (no error message)
[stderr] * Try:
[stderr] > Run with --stacktrace option to get the stack trace.
[stderr] > Run with --info or --debug option to get more log output.
[stderr] > Run with --scan to get full insights.
[stderr] ==============================================================================
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 5m 7s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.
207 actionable tasks: 207 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

**Comment by hwpp** [comment]
저도 같은 증상인데 혹시 해결하셨나요?

**Comment by anymate98** [comment]
안녕하세요. 지난주 라이브러리 버전 업데이트를 진행해 배포했는데 동일한 문제가 일어나시나요?

**Comment by hwpp** [comment]
> 

2.0.3 으로 업데이트 하니 문제가 해결되었습니다~

**Comment by omnmala** [comment]
2.0.2일경우
expo-build-properties 설치 이후
app.json의 'plugins'에
[
        "expo-build-properties",
        {
          "android": {
            "compileSdkVersion": 31,
            "targetSdkVersion": 31,
            "buildToolsVersion": "29.0.2",
            "kotlinVersion": "1.6.10"
          },
          "ios": {
            "deploymentTarget": "13.0"
          }
        }
      ]
위 코드 추가하시면 빌드가 됩니다
이미 업데이트 해서 해결하셨는데 답변이 늦었네요
