### ISSUE TITLE
can't locate file for: -lRNCWebView

### ISSUE THREAD

**Issue by antaehyeon** [iamport/iamport-react-native#19]
1.1.2 버전으로 올린 후 iOS 빌드를 진행하면, 에러가 발생합니다.

can't locate file for: -lRNCWebView
file: -lRNCWebView is not an object file (not allowed in a library)

일단 자체적인 해결으로는 (임시)
1. xCode 프로젝트 내 Libraries 폴더 중 iamprtReactNative.xcodeproj 을 누르고
2. 여기서 Build Phases 에서 libRNCWebView.a 를 제거합니다.
3. 이후 빌드를 진행하니 정상적으로 빌드가 진행됐습니다.

iamport 의 공식적인 해결법이 있습니까?

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.

등록해주신 이슈는 iamport-react-native가 react-native-webview를 링크하고 있었기 때문에 발생한 문제였습니다. 해당 내용은 수정해 v1.1.3-rc에 반영하였습니다.

감사합니다.

**Comment by antaehyeon** [comment]
빠른 피드백 및 수정 감사드립니다 :)
