### ISSUE TITLE
Did not receive response to shouldStartLoad in time 에러 확인요청

### ISSUE THREAD

**Issue by comet0704** [iamport/iamport-react-native#191]
사용한 기기 : ios
1월 20일까지는 결제창이 떠서 결제까지 진행되었는데
1월 25일 이후에 확인해보니 loading 화면이 잠깐 떴다 사라지기만 합니다.
Did not receive response to shouldStartLoad in time, defaulting to YES
라는 warning을 로그창에 찍으면서 해당 현상이 나타나던데 확인해주시면 감사하겠습니다.

https://user-images.githubusercontent.com/45985997/215368104-04343fab-378a-4c92-ae0a-9cfffb5cb486.MP4

**Comment by anymate98** [comment]
안녕하세요. 해당 결제를  발생시킨 결제 파라미터를 확인해볼 수 있을까요?

**Comment by comet0704** [comment]
{"amount": 11920, "app_scheme": "com.sharetown.org", "buyer_addr": "", "buyer_email": "livestrongdavid@gmail.com", "buyer_name": "배재영", "buyer_tel": "010-0000-0006", "digital": true, "merchant_uid": "test", "name": "에그인헬 파스타 2인분 결제", "niceMobileV2": true, "pay_method": "card", "pg": "html5_inicis", "tax_free": 11920}

입니다.

**Comment by anymate98** [comment]
앱 안에서 웹뷰 실행 도중 뭔가 블로킹되는 작업이 있으면 해당 증상이 발생할 수 있을 것으로 생각이 되는데 짐작가는 부분이 있으신가요? 25일 이후부터 결제가 되지 않는다고 하셨는데 이 기간 중 코드의 변화가 있었는지 확인하고 싶습니다.

**Comment by comet0704** [comment]
코드는 변경시킨 부분이 없습니다.
연휴전에 3대의 아이폰 기기에서 결제 정상동작확인하고 앱 업데이트 제출하였습니다.
이후 연휴 끝나고 확인해보았는데 해당 현상이 발생하더군요.

사용한 버전은 아래와 같습니다.
"react-native-webview": "^11.23.1",
"iamport-react-native": "^2.0.0",

**Comment by anymate98** [comment]
버전 공유 감사합니다. 업데이트 제출 전과 후의 현상 모두 로컬 기기에서 발생한 것일까요?

**Comment by comet0704** [comment]
로컬 기기라는 의미를 바로 해석하지 못했습니다만,
개발을 위해 개발기기에서 정상동작확인했고 이후 테스트플라이트에 업로드하여 2대의 기기에서 정상동작 확인했습니다.
이후 해당 현상이 2대의 기기에서 모두 발생하여 원인을 찾기위해 개발기기에서 디버깅모드로 실행한 결과 위에 전달드린 로그가 찍혔습니다.
이리하여 도합 3대의 기기에서 해당 현상이 나타나게 되었습니다.

**Comment by anymate98** [comment]
앱에서 사용하시는 react랑 react-native 버전도 같이 올려주실 수 있나요?

**Comment by comet0704** [comment]
"react": "17.0.2",
"react-native": "0.67.4"
입니다.

**Comment by anymate98** [comment]
꽤 오래전부터 있던 [이슈](https://github.com/react-native-webview/react-native-webview/issues/124#issuecomment-1401064976)로 파악이 되는데요 현재 react-native 0.67.4를 사용하고 계시니까 링크의 해결책처럼 웹뷰 버전을 조금 변경해서 결제창이 잘 뜨는지 확인해보면 좋을 것 같습니다.

**Comment by comet0704** [comment]
webview 버전을 조금 변경시켜도 안되어서요.
문제로 되는것은 동일한 서비스내에서 본인인증서비스는 정상동작하는데 결제만 해당 이슈가 발생하는것으로 보아 이 라이브러리내의 이슈는 아닐지 문의드립니다.

**Comment by hyp3rflow** [comment]
@comet0704 안녕하세요, 팀 내부에서는 해당 이슈가 재현이 되지 않고 있어 해결 방안 모색에 어려움을 겪고 있는 점 양해 부탁드립니다.
> 더우기 되던것이 안되다보니 웹뷰에서 사용하는 웹사이트쪽 변경이 있지 않았을까 검토를 해주시면 감사하겠습니다.

해당 기간 중 서비스 배포는 없었던 것으로 파악되었습니다.

말씀주신 내용을 토대로 미루어 보았을 때 본인인증 웹뷰의 설정과 최대한 맞추어보면 해결될 수도 있지 않을까 싶은데요.
가능하시다면 아래 방법을 따라 시도해보실 수 있으실까요?
- node_modules/iamport-react-native/src/components/Payment/index.tsx 로 이동해주세요.
- `onShouldStartLoadWithRequest`로 검색하신 후, 위의 라인에 `startInLoadingState`을 넣어주세요.
- RN 빌드 캐시를 삭제하신 후 테스트를 진행해주세요.

개발 환경으로 인해 부득이하게 진행할 수 없다면 답글 부탁드립니다.

**Comment by comet0704** [comment]
네, 말씀주신대로 시도해보았으며 현상은 동일하군요.
위 이미지에 보이는 console.log 부분을 열어두었을때 url이 아래와 같이 찍히던데 저것이 혹시 정상인지 확인해주실수 있을까요?
url: about:blank

**Comment by hyp3rflow** [comment]
네 빈 화면에 JavaScript SDK를 실행시키는 스크립트만 삽입하고 있어 `about:blank`로 찍히는 것이 정상작동입니다.

**Comment by comet0704** [comment]
`        <IMP.Payment
          userCode={"*****"} // 가맹점 식별코드
          // tierCode={'AAA'}      // 티어 코드: agency 기능 사용자에 한함
          data={data}             // 결제 데이터
          callback={this.callback}     // 결제 종료 후 콜백
        />`
여기 가맹점 식별코드가 문제이군요.
저 값을 다른 코드로 입력하여 진행하면 되는데 저희 프로젝트의 식별코드만 사용하면 위와 같은 에러가 나타나네요.
![image](https://user-images.githubusercontent.com/45985997/215476456-76686518-e3e0-4d1b-89fb-0ce6dd5968ea.png)
요건 되느는 경우의 url 로그이고
![image](https://user-images.githubusercontent.com/45985997/215476613-8a676710-2e94-4be5-babe-991ffd91077b.png)
요건 안되는 경우의 로그인데 보시다싶이 안되는 가맹점 식별코드의 경우에는 하단 2개의 url이 빠졌습니다.
그래서 나타나는 오류인데 이렇게 되면 pg사쪽 문제일까요?
확인방향을 어떻게 정해야 할지 알려주시면 감사하겠습니다.

**Comment by hyp3rflow** [comment]
@comet0704 해당 URL 로그는 가맹점의 PG 설정에 따라 요청하는 URL이 다를 수 있습니다.
확인을 위해 사용하고 계신 가맹점 식별 코드 정보를 support@iamport.kr 으로 보내주실 수 있으실까요?

**Comment by comet0704** [comment]
해당 이메일로 보내드렸습니다.

**Comment by hyp3rflow** [comment]
@comet0704 문의주신 이메일을 통해 답변 보내드렸습니다.

**Comment by comet0704** [comment]
분석해주신 덕분에 PG사쪽 문제인것으로 확인이 되었고 해결방도를 찾았습니다.
감사드립니다.
