### ISSUE TITLE
injectJavaScript를 통해 주입된 스크립트에서 (iamport js sdk에서 선언한)IMP를 찾지못하는 이슈가 간헐적으로 발생합니다.

### ISSUE THREAD

**Issue by YangJonghun** [iamport/iamport-react-native#193]
현재 webview에서 사용 중이신 `onLoadEnd`에서 주로 `injectJavaScript`를 통해
```typescript
webview.current?.injectJavaScript(`
  setTimeout(function() {
    ...IMP 사용 코드...
  });
`);
```
와 같은 방식으로 코드를 사용중이신데
```typescript
  export const WEBVIEW_SOURCE_HTML = `
<html>
  <head>
    <meta http-equiv='content-type' content='text/html; charset=utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <script type='text/javascript' src='https://cdn.iamport.kr/v1/iamport.js'></script>
  </head>
  <body></body>
</html>
`;
```
webview에서 로드하는 html은 위와 같기 때문에 `iamport js sdk`의 로드상태에 따라 IMP를 못찾는 경우가 간헐적으로 발생합니다. (`RNWebView`의 prop중 `cacheEnabled`의 기본값은 `true`이기 때문에 처음 로드시에만 발생할 경우가 많지만 사용자측에서 강제로 이 prop의 default값을 변경하면 더 자주 발생할 수 있습니다)
아마 `injectJavascript`를 통해 삽입된 스크립트가 `iamport js sdk`를 불러오고 호출하는 스크립트보다 먼저 동작하기 때문에 `setTimeout`으로 처리하셨을거라 생각되는데 window load이벤트나 `DOMContentLoaded`이벤트의 리스너 동작으로 처리해주시는게 이 버그를 막는데 보다 적합하지 않을까 생각됩니다.

+) `Payment`와 `Certification` 컴포넌트에서 사용하는
```
const [isWebViewLoaded, setIsWebViewLoaded] = useState(false);
```
위 state는 렌더링에 영향을 주지 않아서 useState가 아닌 방식으로 수정되어도 좋을 것 같습니다.

**Comment by YangJonghun** [comment]
일반적인 상황에 모두 발생하는 것은 아니고 react-native-webview의 onLoadEnd 동작 시점이 Android targetSdkVersion이 31인 경우에 달라져서 발생하는 문제였습니다.

**Comment by YangJonghun** [comment]
react-native-webview쪽에서 Android의 경우 onLoadEnd가 콘텐츠로드가 끝나기 전에 호출되는 것으로 보이네요
(react-native-webview@11.0.0 는 정상 동작 / react-native-webview@11.26.1 에서는 위와같이 동작)

**Comment by YangJonghun** [comment]
react-native-webview신버전쪽에 버그가 있어 Android의 경우 onLoadEnd가 두번 호출되는 것으로 보이네요
(react-native-webview@11.0.0 는 정상 동작 / react-native-webview@11.26.1 에서는 위와같이 동작)
react-native-webview쪽 이슈긴하나 iamport sdk쪽에서도 유연하게 대응되도록 수정이 되면 좋을 것 같습니다.

**Comment by YangJonghun** [comment]
react-native-webview신버전에서 Android의 경우 onLoadEnd가 두번 호출되는 것으로 보이네요
(react-native-webview@11.0.0 는 정상 동작 / react-native-webview@11.26.1 에서는 위와같이 동작)
react-native-webview쪽 이슈긴하나 iamport sdk쪽에서도 유연하게 대응되도록 수정이 되면 좋을 것 같습니다.

**Comment by hyp3rflow** [comment]
@YangJonghun 안녕하세요, 리포트해주셔서 감사드립니다.

내부적으로 테스트한 결과 iamport-react-native 레포 내에 있는 example에서는 버전을 올리더라도 onLoadEnd가 두번 올라가는 이슈를 재현할 수 없었고, 말씀주신 window.onload 또는 DOMContentLoaded 이벤트에 대해서도 테스트해보았을 때 항상 onLoadEnd가 이후에 호출되는 것을 확인했습니다.

다만, 어제 올려주신 'onLoadEnd가 두번 호출되는 현상'에 따라 미루어보았을 때, react-native-webview@11.0.0에는 없는 코드인 [WebviewShared.tsx#L149-L188](https://github.com/react-native-webview/react-native-webview/blob/9051762cc4b906d957d6297b217bf67c6f12ed8e/src/WebViewShared.tsx#L149-L188)에 따라 onLoadingError인 경우에도 onLoadEnd가 실행되기 때문에, 앱 구현 혹은 환경 상의 문제로 인해 로드가 실패하는 것은 아닌지 의심됩니다.

가능하시다면 node_modules 안에 있는 iamport-react-native 코드를 수정하여 테스트해주실 수 있으실까요?
src/components/Certificatication.tsx (결제 시에 문제가 발생한다면 Payment.tsx를 수정해주세요)의 WebView onLoadEnd props로 전달되는 함수에 아래와 같이 수정하시면 로그를 볼 수 있습니다.
```typescript
onLoadEnd={(event) => {
  console.log('onLoadEnd event!', event.nativeEvent); // here
  if (!isWebViewLoaded) {
```
이렇게 URL과 함께 로그가 출력되며, 만약 event에 `code` property가 있다면 위의 원인으로 확신할 수 있을 것 같습니다.
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/49385012/220823166-d36b610d-b64b-4445-93a2-092107149356.png">

부득이하게 테스트가 불가능한 상황이시라면 편하게 말씀주세요. 감사합니다 :bow:

**Comment by YangJonghun** [comment]
빠르게 확인해주셔서 감사합니다!
일단 말씀주신대로 iamport-react-native repo의 example을 확인 해봤을 땐 문제가 없네요.
(이슈 작성시 iamport-react-native v1.6.2버전에 문제가 있어 load이벤트가 동작하도록 patch해서 사용중이었으나 현재 v2.0.4로 업데이트하고 위와같은 이슈가 없어진 것을 확인했습니다)
example로 디버깅을 먼저해봤으면 정확한 원인 파악이 보다 빨랐을텐데 번거로움을 드려 죄송합니다.
아마 다른 안드로이드 dependency가 웹뷰 동작에 간섭을 하고 있었을 가능성도 있을 것 같네요.
이 이슈는  iamport-react-native의 이슈가 아니기 때문에 close처리하겠습니다.
감사합니다.
