### ISSUE TITLE
안드로이드는 언제쯤 구현이 완료될까요?

### ISSUE THREAD

**Issue by yansfil** [iamport/iamport-react-native#2]
안드로이드 구현은 언제쯤 완료될까요?

**Comment by jangbora** [comment]
feature 브랜치의 내용을 아직 master 브랜치로 병합하지 못하였습니다. (추가 테스트 중에 있습니다)

https://github.com/iamport/iamport-react-native/tree/feature/merge-android-n-ios
우선 feature 브랜치로부터 설치해 사용해주셔야 할 것 같습니다. (실제 이용 중인 유저도 있습니다)

**Comment by yansfil** [comment]
감사합니다!
