### ISSUE TITLE
react native fbsdk 나react-native-facebook-account-kit 와 같이 사용시 오류

### ISSUE THREAD

**Issue by pyeonjaesik** [iamport/iamport-react-native#20]
안드로이드에서 위 api 와 iamport-react-native 를 같이 사용하면 오류가 납니다.
어떤 오류이냐면...
페이스북 로그인이나 핸드폰 번호인증 로그인 후 앱이 그냥 꺼져버립니다... 이 경우 왜 그런거죠..?

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.

말씀해주신 상황만으로는 판단이 어려워 몇가지 질문을 드리겠습니다.

1. 현재 사용하고 계시는 iamport-react-native 버전이 몇인가요?
2. IOS에서는 잘 되는데 안드로이드에서만 문제가 발생한다는 말씀이신가요?
3. 아임포트 모듈이 삭제된 상황에서는 정상적으로 동작하는걸 확인하셨나요?
4. 앱이 꺼지기 직전 로그를 찍어보시고 첨부해주시면 디버깅에 편할 것 같습니다.

감사합니다.

**Comment by pyeonjaesik** [comment]
1. "^1.1.3-rc" 입니다.
추가적으로  package.json의 dependencies도 기입하겠습니다.
  "dependencies": {
    "@react-native-community/async-storage": "^1.5.0",
    "adm-zip": "^0.4.13",
    "iamport-react-native": "^1.1.3-rc",
    "lottie-react-native": "^2.6.1",
    "plist": "^3.0.1",
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-facebook-account-kit": "^1.1.0",
    "react-native-fast-image": "^6.0.3",
    "react-native-fbsdk": "^0.8.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-image-resizer": "^1.0.1",
    "react-native-linear-gradient": "^2.5.4",
    "react-native-material-ripple": "^0.8.0",
    "react-native-simple-toast": "0.0.8",
    "react-native-status-bar-height": "^2.3.1",
    "react-native-swiper": "^1.5.14",
    "react-native-thumbnail": "^1.1.3",
    "react-native-video": "^4.4.2",
    "react-native-webview": "^5.12.1",
    "react-navigation": "^3.11.0",
    "react-redux": "^7.1.0",
    "redux": "^4.0.1",
    "xcode": "^2.0.0"
  },


2. 네 IOS에는 잘 작동하지만 안드로이드에서는 잘 작동하지 않습니다.

3. 네 확인하였고 그땐 잘 작동합니다.
4. 로그를 찍어보았지만 어떠한 오류도 발생하지않고 앱이 꺼져버려 좀 난감하네요...
   하지만 이해를 돕기위해 제가 사용하는 함수를 적어두겠습니다.
    LoginManager.logInWithReadPermissions(["public_profile"]).then(
      function(result) {
        if (result.isCancelled) {
          console.log("Login cancelled");
        } else {
          AccessToken.getCurrentAccessToken().then(
            ((data) => {
                ///my code... 이하생략
              })
              .catch((error) => {
                console.error(error);
              });        
            })
          )
        }
      }.bind(this),
      function(error) {
        console.log("Login fail with error: " + error);
      }
    );

**Comment by pyeonjaesik** [comment]
근데 앱이 항상 꺼지는게 아니라 어쩌다가 한번쯤은 로그인이 되긴합니다... (??)
그래서 이 api( iamport-react-native )를 이용하지 않고 웹뷰를 이용하여서 구현해 보았는데요. 그 때는
카드 결제시 보안 프로그램 설치 창에서
'다음 화면으로 진행이 안되면 브라우져 설정에서 타사쿠기 허용으로 선택 후 이용하시기 바랍니다' 라는 오류 문구가 뜹니다. 이건 어떻게 해결하면 될까요?

**Comment by SoleeChoi** [comment]
답변 감사드립니다.

**Comment by SoleeChoi** [comment]
답변 감사드립니다.

**Comment by SoleeChoi** [comment]
답변 감사드립니다.

저희 쪽에서 재현이 어려워,
프로젝트 전체를 아임포트 서포트 이메일(support@iamport.kr)로 보내주시면 디버깅 해 보겠습니다.
테스트 결제에 필요한 로그인 정보 등이 있다면 알려주시면 감사하겠습니다.

감사합니다.

**Comment by pyeonjaesik** [comment]
프로젝트 전체를 드리기엔 곤란하다는 점 이해 부탁드립니다.
다만, 제가 올려드린 dependencies 중에서
"react-native-facebook-account-kit": "^1.1.0", 와
"react-native-fbsdk": "^0.8.0", 를 같이 설치한다면 같은 오류를 얻으실 수 있을겁니다.

**Comment by pyeonjaesik** [comment]
1."react-native-fbsdk": "^0.8.0" 설치 및 연동
2."react-native-facebook-account-kit": "^1.1.0" 설치 및 연동
3. "iamport-react-native": "^1.1.3-rc", 설치 및 연동
4. fbsdk 의 LoginManager.logInWithReadPermissions(["public_profile"]).then 실행 시 오류 발생

**Comment by SoleeChoi** [comment]
말씀하신대로 테스트를 진행해보려면,
단순히 설치하고 링킹하는 것 외에
페이스북에 앱을 등록하고 SDK를 설정해야 하는데
그 과정이 생각보다 많이 복잡하네요.

프로젝트 전체 전달이 부담스러우시다면,
오류가 나는 부분만 따로 떼서 프로젝트 만들어주시고
아임포트 서포트 메일(support@iamport.kr)로 보내주시면 감사하겠습니다.

현재  `LoginManager.logInWithReadPermissions`을 호출했을때 앱이 꺼진다고 하셨으니
해당 메소드에서 로그를 찍어보시거나 RN debugger에서 콘솔을 찍어보신 후
관련 에러 내용이 있으시다면 전달 부탁드립니다.

감사합니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.

일단 충돌이 발생한다고 의심하신 두 가지 라이브러리 중에
`react-native-fbsdk`만 설치 및 연동 후
아임포트 라이브러리와 함께 사용해 보았습니다.
단순히 `LoginManager.logInWithReadPermissions`을 호출하는데 있어
`react-native-facebook-account-kit`은 필요하지 않은 것 같아서요.
그런데 `LoginManager.logInWithReadPermissions` 호출 후
앱이 꺼지거나 튕기는 현상은 발생하지 않아서 재현이 어려운 상황입니다.

**Comment by pyeonjaesik** [comment]
react-native-facebook-account-kit 의 핸드폰인증 함수인 RNAccountKit.loginWithPhone()
와
이메일 인증 함수인 RNAccountKit.loginWithEmail()
를 사용 할때도 같은 오류가 발생합니다.  따라서 react-native-facebook-account-kit 도 같이 설치해야 오류가
발생하는 것이 의심됩니다.
또한 react-native-fbsdk는 버전이 최신버전이 아닙니다. 아래  참고 부탁드립니다.

"react-native-facebook-account-kit": "^1.1.0",

"react-native-fbsdk": "^0.8.0",

2019년 7월 9일 (화) 오후 1:09, Solee Choi <notifications@github.com>님이 작성:

**Comment by pyeonjaesik** [comment]
IAMPORTPROJECT.zip
<https://drive.google.com/file/d/1HRNXKEwbFwLhyOG0aZgT2BG0yz8dQLYM/view?usp=drive_web>
"react-native-facebook-account-kit": "^1.1.0",

"react-native-fbsdk": "^0.8.0",만 설치되어있는 파일 보내드립니다.

2019년 7월 9일 (화) 오후 1:15, 편재식 <vuswotlr@gmail.com>님이 작성:

**Comment by SoleeChoi** [comment]
감사합니다. 확인 후 빠른 시일 내에 안내드리도록 하겠습니다.

**Comment by pyeonjaesik** [comment]
네 감사합니다 ^^


2019년 7월 9일 (화) 오후 1:26, Solee Choi <notifications@github.com>님이 작성:

**Comment by joks1997** [comment]
저도 유사한 오류가 나네요 저는 react-native-facebook-account-kit은 사용하고 있지 않습니다. 안드로이드 스튜디오에 표시되는 오류 함께 첨부드립니다.

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=9001, result=0, data=Intent { (has extras) }} to activity {com.***.***/com.***.***.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.iamport.webviewclient.IamportWebViewClient.bankPayPostProcess(int, int, android.content.Intent)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4360)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.iamport.webviewclient.IamportWebViewClient.bankPayPostProcess(int, int, android.content.Intent)' on a null object reference
        at com.iamport.IamportViewManager.onActivityResult(IamportViewManager.java:36)
        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:262)
        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:703)
        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:124)
        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:75)
        at com.***.***.MainActivity.onActivityResult(MainActivity.java:20)
        at android.app.Activity.dispatchActivityResult(Activity.java:7454)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.

디버깅 결과 해당 이슈는 페이스북 연동을 위해 유저의 MainActivity에서 onActivityResult를 호출할때
아임포트의 onActivityResult가 함께 호출되서 발생하는 문제였습니다.

아임포트는 이를 해결하기 위해 startActivityForResult 호출시,
requestCode를 유니크한 값으로 설정하고
onActivityResult에서 이를 구분해 관련 로직을 처리하도록 수정하였습니다.

해당 내용은 v1.1.4-rc.0 버전에 반영되었으니 확인 부탁드립니다.
버그 리포트에 감사드립니다.
