### ISSUE TITLE
토스페이먼츠 테스트 안됨

### ISSUE THREAD

**Issue by IbrahimaWane** [iamport/iamport-react-native#204]
안녕하세요?
React Native 프로젝트에서 iamport를 사용하고 있는데"tosspayments"로 테스트하면 "결제 창 호출에 실패했습니다. 채널 정보를 조회할 수 없습니다."라고 표시됩니다. 오류 코드는 F500입니다. pg 값을 "tosspayments"로 설정했지만 "kicc" 또는 "tosspay"로 바꾸면 제대로 작동합니다. 무엇은 문제일까요?

**Comment by anymate98** [comment]
어드민의 "결제 연동" 메뉴에 토스페이먼츠가 제대로 설정되어있는지 확인이 필요합니다.

**Comment by IbrahimaWane** [comment]
답변 감사합니다.
설정은 이렇게 했는데 맞나요?

<img width="800" alt="스크린샷 2023-04-20 오후 2 24 09" src="https://user-images.githubusercontent.com/35750957/233266078-c770aa0f-095d-4787-806f-41996ecf9d45.png">

**Comment by anymate98** [comment]
아뇨 이건 uplus입니다. (구)가 붙지 않은 것으로 해주세요.

**Comment by IbrahimaWane** [comment]
해결되었습니다. 감사합니다~
