### ISSUE TITLE
안드로이드 현대카드 일반결제 시 팅깁니다.

### ISSUE THREAD

**Issue by komo3344** [iamport/iamport-react-native#206]
## Sentry Error log
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/33312219/235844053-77096c5d-42ef-408b-8190-47fa7f632dfa.png">

## Solution
Problem Description
It looks like there's a TypeError in your JavaScript code. The error message says that you're trying to split a property of undefined. This means that the variable you're trying to access doesn't have a value.

The error happened in the IamportUrl function in your index.android module, in the index.android.bundle file, on line 1. The function then calls the onShouldStartLoadWithRequest function before the error occurs.

Proposed Solution
To fix this issue, you need to make sure that the variable you're trying to access actually has a value before trying to split it. You can do this by adding a check for undefined before the split function call.

Here's an example of how you can modify your code:
```
if (myVariable !== undefined) {
  var myArray = myVariable.split(",");
}
```
You should add this check wherever you're trying to split the undefined value.

To prevent similar issues in the future, it's always a good idea to double-check that your variables have values before trying to access or manipulate them. You can also use TypeScript to add type annotations to your code and catch potential errors before they even happen.

**Comment by anymate98** [comment]
현재 사용하는 iamport-react-native의 버전, 사용하고 있는 또는 문제가 발생하는 pg사, 일반결제의 어떤 과정에서 문제가 발생하는지 등을 알려주시면 감사하겠습니다.

**Comment by komo3344** [comment]
2.0.1 버전입니다
