### ISSUE TITLE
v1.1.4-rc.0 / 결제 에러

### ISSUE THREAD

**Issue by pyeonjaesik** [iamport/iamport-react-native#21]
card 결제 시 결제 창이 나오지 않고 바로 콜백함수가 실행됩니다.
IOS와 Android 모두에서 같은 오류가 발생됩니다. 
모든 pg 사를 테스트해보진 않았습니다. 다만 kakao , danal_tpay는 위 에러가 발생됩니다.
하지만 LGU+는 정상적으로 작동합니다.
오류 수정 혹은 제가 놓치고 있는 부분을 알려주시길 부탁드리겠습니다.

조금이라도 도움이 되기 위해서 제 코드를 적어놓겠습니다.
          <IMP.Payment
              userCode={'***********'} 
              data={{
                pg: 'kakao', // danal_tpay 로 바꿔도 같은 오류 발생.
                pay_method: 'card',
                name: '아임포트 결제데이터 분석',
                merchant_uid: `mid_${new Date().getTime()}`,
                amount: this.state.pay_amount,// state값에 따라서 변하는 값입니다.
                buyer_name: '홍길동',
                buyer_tel: '01012345678',
                buyer_email: 'example@naver.com',
                buyer_addr: '서울시 강남구 신사동 661-16',
                buyer_postcode: '06018',
                app_scheme: 'example',
                digital:'false',
              }} // 결제 데이터
              callback={()=>{alert('success')}} // 결제 종료 후 콜백
              loading={{
                message: '잠시만 기다려주세요...', // 로딩화면 메시지 
                image: require('../assets/best.png') // 커스텀 로딩화면 이미지
              }}
          />

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.

콜백함수에 파라메터로 전달되는 response를 찍어서 알려주세요.
callback={response => console.log(response)}
참고로 이거와는 별개지만, app_scheme값은 귀하의 것으로 바꿔 입력하셔야 합니다.

감사합니다.

**Comment by pyeonjaesik** [comment]
대시보드의 시스템 설정에서
복수 Pg로 간편결제 네이버페이[주문형]과  [간편결제]카카오페이를 추가하였습니다.
네이버페이[주문형] 일때는
        <IMP.Payment
              userCode={'imp77888976'} // 가맹점 식별코드
              data={{
                pg: 'naverco',
                pay_method: 'card',
                name: '아임포트 결제데이터 분석',
                merchant_uid: `mid_53423542-529852-49214`,
                amount: '1100',
                buyer_name: '홍길동',
                buyer_tel: '01012345678',
                buyer_email: 'example@naver.com',
                buyer_addr: '서울시 강남구 신사동 661-16',
                buyer_postcode: '06018',
                app_scheme: 'example',
                digital:false,
              }} // 결제 데이터
              callback={(rsp)=>{
                console.log('callback:')
                console.log(rsp);
              }} // 결제 종료 후 콜백
              loading={{
                message: '잠시만 기다려주세요...', // 로딩화면 메시지 
                image: require('../assets/best.png') // 커스텀 로딩화면 이미지
              }}
            /> 
의 코드로 하였고 
{error_code: "[ERR-OR-100001] 가맹점ID 정보가 없습니다.", error_msg: "[ERR-OR-100001] 가맹점ID 정보가 없습니다.", success: "false"} 라는 에러가 뜹니다.



[간편결제]카카오페이 결제는 
위 코드에서 pg 파라미터를 'kakao'로만 바꿔 진행하였고
똑같은 에러같은 에러가 발생합니다.

danal_tpay는 다시 해보니 정상적으로 작동하네요....

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.

[간편결제] 카카오페이의 경우, 시스템 설정시 테스트모드여도 `가맹점코드(CID)`를 입력하셔야 합니다.
아임포트 관리자페이지 시스템 설정에서 아래 환경에 맞게 해당 설정을 추가해주세요.

- 일반결제 : `TC0ONETIME`
- 정기결제 : `TCSUBSCRIP`

위 내용은 아임포트 [(구) 메뉴얼](https://github.com/iamport/iamport-manual/blob/master/%EC%9D%B8%EC%A6%9D%EA%B2%B0%EC%A0%9C/sample/kakao.md)에 명시되어 있는데 [(신) 메뉴얼](https://docs.iamport.kr)에 아직 업데이트 하지 못해 혼란을 드려 죄송합니다.

감사합니다.
