### ISSUE TITLE
네이버 페이 정기 걸제

### ISSUE THREAD

**Issue by purrsong-chong** [iamport/iamport-react-native#211]
네이버 페이 정기 결제 창을 띄우고 싶은데,
관련 파라미터가 없네요 ㅠ

https://developer.pay.naver.com/docs/v2/api#recurrent-recurrent_register_window

payType이라는 파라미터가 있어야 하는 거 같은데
어떻게 해야할까요?

**Comment by anymate98** [comment]
안녕하세요. 포트원의 경우 일반결제와 정기결제의 구분을 주로 customer_uid로 하고 있습니다. 따라서 customer_uid 파라미터를 입력해주시면 결제창을 정기결제로 띄우실 수 있을 것으로 생각합니다.

**Comment by purrsong-chong** [comment]
customer_uid 파라미터는 입력이 되어있는 상태에요..
혹시 네이버 페이는 일반결제용 정기결제용 chainId가 따로 있어야하는건가요??

**Comment by anymate98** [comment]
chain id의 경우 각각 발급될 것입니다. 어드민 결제연동 페이지에서 네이버페이 연동을 할 경우 chain id를 입력하는 공간이 있습니다.

**Comment by purrsong-chong** [comment]
@anymate98 chain id 때문이였네요. 감사합니다!
