### ISSUE TITLE
Naver pay production mode

### ISSUE THREAD

**Issue by purrsong-chong** [iamport/iamport-react-native#212]
naver pay production chainId로 연결시 
"유효하지 않은 가맹점입니다."라는 문구가 뜹니다.

naver pay 문서를 보내 mode라는 파라미터를 입력해야하는데, iamport에서는 어떤 파라미터를 입력해야할까요?

**Comment by anymate98** [comment]
사용하신 결제 채널이 테스트 모드일 것으로 추측되는데 이를 실 연동 모드로 바꿔주셔야 합니다.

**Comment by purrsong-chong** [comment]
결제 채널이 테스트 모드 실연동이 함께 있을때 해당 현상이 일어나네요 ㅠ
테스트 모드를 삭제하니 해결되었습니다.
