### ISSUE TITLE
react native firebase와 연동시 에러

### ISSUE THREAD

**Issue by youngsupchoi** [iamport/iamport-react-native#225]
```bash
npm install --save @react-native-firebase/app
yarn add @react-native-firebase/app
```

```bash
npx pod-install
```

npx pod-install을 하니 아래와 같은 에러가 발생하였습니다

<img width="1371" alt="image" src="https://github.com/iamport/iamport-react-native/assets/112808338/0f27351a-d70e-4df4-94a7-d5bbf272da1c">

구글링 한 결과 아래 코드를 ios/podfile에 넣으라고 하여 해당 코드를 추가하고 다시 npx pod-install을 하였습니다.

```ruby
$RNFirebaseAsStaticFramework = true

  config = use_native_modules!
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  use_frameworks! :linkage => :static

```

위 작업을 거치고 다시 npx pod-install을 실행하였을때 아래와 같은 에러가 발생했습니다.

<img width="687" alt="image" src="https://github.com/iamport/iamport-react-native/assets/112808338/3e1960c7-520a-4a50-ac0b-5842c0b90fcd">

**Comment by anymate98** [comment]
문제 재현을 위해 예제 앱애서 동일한 의존성을 추가하고 npx pod-install을 실행해봤는데 동일한 에러가 발생했습니다.
그 후 config 아래에 `pod 'GoogleUtilities', :modular_headers => true`만 넣고 다시 pod install을 해봤는데 이번에는 정상 작동했습니다.

제가 참고한 [링크](https://velog.io/@qkr135qkr/firebase를-iOS에-적용하면서-맞닦들인-문제들)입니다.

**Comment by youngsupchoi** [comment]
감사합니다 해결했습니다.
