### ISSUE TITLE
Example 할부 결제 문의

### ISSUE THREAD

**Issue by yoonjaepark** [iamport/iamport-react-native#23]
IMP.request_pay 에 param값을 넘길때 

display":{"card_auota":[3]} 

공식 문서를 보면 card_auota 가 아닌 card_quota 이 값인거같은데 수정해야될꺼같습니다.

**Comment by SoleeChoi** [comment]
앗 그렇네용

**Comment by yoonjaepark** [comment]
> 안녕하세요 아임포트입니다.
> 
> 앗 그렇네용 다음 버전업 할때 반영하도록 하겠습니다.
> 
> 타이포 리포트에 감사드립니다.

넵! 관련되서 아임포트 Flutter 용 패키지 RN 패키지 참고해서 만들어보았습니다.

flutter dev
https://pub.dev/packages/flutter_iamport

깃허브 주소
https://github.com/yoonjaepark/flutter_iamport
