### ISSUE TITLE
iOS 네이버페이 앱으로 로그인하기 문의

### ISSUE THREAD

**Issue by Axiivy-Jaeseok** [iamport/iamport-react-native#235]
현재 구조는 react-native-webview를 통해서 결제 페이지에서 결제 방식 선택 후 웹에서 react-native로 payment data가 담긴 data를 postMessage하여 앱에서 보여주고 있습니다.

네이버페이를 선택할 경우 안드로이드에서는 네이버 앱으로 로그인하기 클릭 시 네이버 앱이 정상적으로 실행됩니다.

다만, iOS에서는 네이버 앱으로 로그인하기 클릭 시 네이버 앱이 아닌 앱스토어 네이버 앱으로 연결됩니다. 현재, 네이버 앱 버전은 최신버전으로 유지하여도 동일 현상이 발생합니다.

이 부분에 대한 해결책이나 방법이 있나요?

**Comment by anymate98** [comment]
Info.plist의 LSApplicationQueriesSchemes에 네이버 앱이 등록되어 있나요?
`naversearchthirdlogin`을 추가해주시면 됩니다.

**Comment by Axiivy-Jaeseok** [comment]
iOS설정하기 페이지에 해당 내용이 없어서 놓친 것 같습니다. 감사합니다!
