### ISSUE TITLE
본인인증 시 인증 실패가 발생합니다.

### ISSUE THREAD

**Issue by ShimHyesu** [iamport/iamport-react-native#240]
iamport-react-native 의 IMP.Certification 컴포넌트 호출 시 loading화면 이후 인증 모듈이 나오지 않습니다.
<br>

결과값은 다음과 같이 넘어옵니다.

`{"error_code": "9015", "error_msg": "다날 서버로부터 받은 응답이 올바르지 않습니다. [인증실패] 업체정보에 이상이 있습니다. 해당 서비스 업체로 문의하여 주십시오.", "imp_uid": "imp_025072183123", "merchant_uid": "mid_1708784068836", "success": false}`
<br>

## 테스트 환경

Android, iOS

iOS의 경우 해당 [부분](https://github.com/iamport/iamport-react-native/blob/main/manuals/SETTING.md)을 참고하여 설정하였습니다.
<br>

## 모듈 버전

"iamport-react-native": "^2.0.11",
"react-native-webview": "^13.8.1",
"react": "18.2.0",
"react-native": "0.72.10",
<br>

## Source
```javaScript
const CertificationScreen = ({ navigation }) => {
    /* [필수입력] 본인인증에 필요한 데이터를 입력합니다. */
    const data = {
        merchant_uid: `mid_${new Date().getTime()}`,
        company: '아임포트',
        carrier: 'SKT',
        name: '홍길동',
        phone: '01012341234',
        min_age: '',
    };

    const Loading = () => {
        return (
            <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
                <Text>Loading...</Text>
            </View>
        )
    }

    function callback(response) {
        console.log('response', response);

        //navigation.replace('CertificationResult', response);
    }


    return (
        <IMP.Certification
            userCode={''}  // 가맹점 식별코드
            //tierCode={'AAA'}      // 티어 코드: agency 기능 사용자에 한함
            loading={<Loading />} // 로딩 컴포넌트
            data={data}           // 본인인증 데이터
            callback={callback}   // 본인인증 종료 후 콜백
        />
    );
}

export default CertificationScreen
```
가맹점 식별코드는 관리자 콘솔 - 내 식별코드 작성하고 실행했습니다.

**Comment by anymate98** [comment]
안녕하세요. 콘솔에서 설정할 수 있는 다날 휴대폰 소액결제 및 본인인증 테스트 채널은 결제 용도이며 본인인증은 지원하지 않습니다. 다날 휴대폰 본인인증은 유료이므로 다날에서 본인인증용 cpid를 발급받아 테스트하셔야 합니다.

**Comment by ShimHyesu** [comment]
확인했습니다. 감사합니다.
