### ISSUE TITLE
migration issue

### ISSUE THREAD

**Issue by SungilJung** [iamport/iamport-react-native#245]
현재 1.6.4 -> 2.0.12으로 버전업하는 작업을 진행중인데 다음과 같은 이슈가 있어서 문의드립니다.

[1.6.4]
모델의 속성값이 옵셔널
<img src="https://github.com/iamport/iamport-react-native/assets/7083445/66082ce7-e266-4b44-a301-e3dfe7c71e1b" width="800" />

[2.0.0.rc.0]
모델의 속성값이 필수로 변경
<img src="https://github.com/iamport/iamport-react-native/assets/7083445/ca229595-18d6-4f38-8632-c816c67d32d0"
width="800" />

추가로 PaymentData에서 escrow도 옵셔널에서 필수로 변경되었습니다.

다음과 같이 모델이 옵셔널에서 필수로 변경되었을때 어떻게 값을 넣어주면 되나요?
string 타입 -> 빈 문자열
boolean 타입 -> false

이렇게 진행해도 괜찮은걸까요?

**Comment by anymate98** [comment]
네 그렇게 개발해주시면 됩니다.

**Comment by SungilJung** [comment]
@anymate98 빠른 답변 감사드립니다. 🙇‍♂️
