### ISSUE TITLE
다날 SMS 인증 에러

### ISSUE THREAD

**Issue by pddaa297** [iamport/iamport-react-native#246]
```typescript
  return (
    <IMP.Certification
      userCode="발급받은 가맹점 식별코드"
      loading={<... />}
      data={{
        pg: 'danal',
        merchant_uid: `merchant_${new Date().getTime()}`,
      }}
      callback={result => {
        console.log(result);
      }}
    />
  );
```
코드는 예시대로 작성하였습니다. 
다날 본인인증 승인 받고,  CPID, CPPWD 설정하여 실행하였는데 아래와 같이 에러가 납니다.

https://sdk-playground.portone.io/ 여기서 v1이 아닌, v2로 진행하면 잘 작동하는데 v1에서 작동하려면 어떻게 해야 할까요?

`{"error_code": "9015", "error_msg": "다날 서버로부터 받은 응답이 올바르지 않습니다. [인증실패] 업체정보에 이상이 있습니다. 해당 서비스 업체로 문의하여 주십시오.", "imp_uid": "imp_296168469219", "merchant_uid": "merchant_1714381167374", "success": false}`

**Comment by anymate98** [comment]
현재 계정에 다날 본인인증이 테스트용 하나, 실연동 하나, 총 두개 등록되어 있는 것으로 확인했습니다. 우선 다날 본인인증 테스트 계정의 경우 상기의 에러를 발생시키므로 테스트 할 수 없고 실제로 발급받으신 CPID로 테스트하셔야 함을 알려드립니다.
V2에서 본인인증이 정상적으로 진행된 이유는 pg 파라미터가 없고 대신 channelKey를 지정함으로 어떠한 본인인증 채널을 사용할 지 결정할 수 있기 때문입니다. 반면 V1의 경우 pg값으로 danal을 지정하셔도 이미 다날 본인인증 채널이 두개이므로 그 중 테스트 채널이 선택되어 본인인증에 사용된 것으로 보입니다.
다날 테스트 채널을 지우거나 pg 값을 'danal.{CPID}' 형태로 지정하시면 실연동 채널로 본인인증을 진행하실 수 있습니다.

**Comment by pinddFull** [comment]
아 그렇군요. 확인 감사합니다!

**Comment by pddaa297** [comment]
아 그렇군요! 확인 감사합니다.
