### ISSUE TITLE
1.2.0버전 오류 / 안드로이드 m_redirect_url 오류 / 모빌리언스 오류

### ISSUE THREAD

**Issue by kwak914** [iamport/iamport-react-native#26]
1) 1.2.0 버전에서 안드로이드 및 iOS 동일하게 아래와 같은 오류가 뜹니다. (1.2.0 만 발생)
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/12079674/62916355-0a4bce00-bdd3-11e9-8945-e29517de1e53.png)

2) 1.1.4-rc.1 버전 이하 및 1.1.2 이상 버전에서 m_redirect_url 이 없다고 뜹니다. (1.2.0버전은 위의 오류 때문에 확인 불가) (안드로이드만 발생하는 문제, iOS에서는 정상 작동함)
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/12079674/62916454-7cbcae00-bdd3-11e9-9e33-011b99f5dda8.png)

3) 확인한 모든 버전에서 모빌리언스 카드 결제 모듈이 작동하지 않습니다. (바로 휴대폰 결제 첫 화면으로 들어감)
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/12079674/62916472-952cc880-bdd3-11e9-89eb-2ef46c7cdf32.png)

```
const data = {
	pg: "mobilians",
	digital: false,
	pay_method: "card",
	name: "아임포트 결제데이터 분석",
	merchant_uid: "*******",
	amount: "39000",
	buyer_name: "홍길동",
	buyer_tel: "0102345678",
	buyer_email: "example@naver.com",
	buyer_addr: "서울시 강남구 신사동 661-16",
	buyer_postcode: "06018",
	app_scheme: "airstore",
	// [Deprecated v1.0.3]: m_redirect_url
};
```

```
<IMP.Payment
 userCode={"*******"} // 가맹점 식별코드
data={data} // 결제 데이터
callback={this.callback} // 결제 종료 후 콜백
loading={{
		message: "잠시만 기다려주세요...", // 로딩화면 메시지
	}}
/>

```

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.

1.
로딩 파라메터는 컴포넌트 타입으로 변경되었습니다.
해당 내용은 [버전 정보](https://github.com/iamport/iamport-react-native/blob/master/manuals/VERSION.md)와 예제 코드에 안내되어 있습니다.

2. 
1번 내용 수정 후 다시 한 번 확인 부탁드립니다.
참고로 (아시겠지만) m_redirect_url은 v1.0.3부터 deprecated되었습니다. 해당 파라메터는 RN 모듈이 임의로 지정해 처리합니다.

3.
관련 내용 CS로 문의 주시어 답변 메일 보내드렸습니다.
확인 부탁드립니다.

감사합니다.
