### ISSUE TITLE
Example 빌드에러가 계속 발생합니다.

### ISSUE THREAD

**Issue by yansfil** [iamport/iamport-react-native#3]
![kakaotalk_photo_2018-09-13-12-41-21](https://user-images.githubusercontent.com/14955500/45465935-71d84400-b752-11e8-8969-8349b14c0e1a.jpeg)

'components/Home' does not exist in the Haste module map 과 같은 에러들이 계속해서 뜹니다.
해당 소스파일을 보니 경로 설정을 ../components/Home 이런식으로 바꾸면 또 다른 경로에러가 나는듯 합니다. 어떻게 처리하면 될까요? 안드로이드, ios 모두 동일합니다.

**Comment by SoleeChoi** [comment]
아래와 같은 방법으로 예제 프로젝트를 테스트해보시는 것을 추천합니다.
```
- git clone -b feature/merge-android-n-ios https://github.com/iamport/iamport-react-native.git
- cd [아임포트 프로젝트 위치]
- npm install
- cd [아임포트 프로젝트 위치]/example
- npm install
- [아임포트 프로젝트 위치]/example/android에 local.properties 파일을 만들고 sdk 경로 추가(sdk.dir=/Users/[USERNAME]/Library/Android/sdk)
- react-native run-android
```

혹시 다른 방법으로 예제 프로젝트를 테스트하시면서 첨부해주신 이미지와 같은 이슈가 발생하는 경우,
아래 명령어를 통해 다시 한 번 테스트 부탁드립니다.
```
- rm -rf node_modules && npm install
- npm start -- --reset-cache
```

**Comment by SoleeChoi** [comment]
네 맞습니다. IOS가 어떻게 작동이 안되시는지 보다 자세한 설명 또는 이미지를 첨부해주시면 답변이 수월 할 것 같습니다.

**Comment by yansfil** [comment]
해결되었습니다. 감사합니다!
