### ISSUE TITLE
결제 완료후, 결제 화면이 닫히면서 전 페이지로 redirection되는거 같은데 정상적으로 동작하지 않는거 같습니다.

### ISSUE THREAD

**Issue by ijunc2** [iamport/iamport-react-native#30]
이니시스 사용할 경우, URI가 짤려서 호출되고, Paypal에서는 Please m_redirect_param url...
이라는 메세지가 뜨네요.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.

이니시스의 경우, URI가 짤려서 호출된다는게 정확히 어떤 말씀일까요? 어떤 상황에서 뭐가 호출되신다는건지. 또한 짤린 URI는 뭘까요?

말씀하신대로 결제완료 후 결제화면이 닫히는건 맞는데 이전페이지로 이동한다는게 어떤 페이지로 이동을 말씀하시는건가요? 리드미에 안내드린 내용대로, 콜백함수에서 navigation.replace 함수를 호출해 결제 후 결과 페이지로 직접 이동시키셔야합니다. 그렇지 않은 경우 단순히 결제화면이 닫히고 아무런 동작도 하지 않습니다.

페이팔의 경우엔 확인 후 안내드리도록 하겠습니다.

감사합니다.
