### ISSUE TITLE
RN 버전?

### ISSUE THREAD

**Issue by kimho** [iamport/iamport-react-native#34]
가이드에
$ npm install react-native-webview --save // RN v0.60 이상 필수
이렇게 써있는데요..

RN v0.60 이상인 경우 필수로 webview를 설치하라는 얘기인가요?
아니면 webview 방식을 쓰기위해 RN을 v0.60 이상으로 필수로 설치하라는 얘기인가요?
위 주석이 무슨 의미인지 설명 부탁드립니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.

전자가 맞습니다.
RN v0.60이상의 경우, 아임포트 모듈의 원활한 사용을 위해 react-native-webview를 필수로 설치하셔야 합니다.

감사합니다.
