### ISSUE TITLE
iOS13 RNKWKWebView Issue

### ISSUE THREAD

**Issue by giftset** [iamport/iamport-react-native#35]
테스트 모듈 진행이 급한데 부탁드려요ㅠㅠ
<img width="342" alt="Screen Shot 2019-10-16 at 6 20 49 PM" src="https://user-images.githubusercontent.com/36372238/66905979-d3e43680-f041-11e9-92e1-5e6632f40327.png">

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.

음, 혹시 급하시면 일단 react-native-webview를 v7.4.1로 업데이트 해보시겠어요?
iamport-react-native/package.json의 react-native-webview를
현재 5.11.0에서 7.4.1로 업데이트 해보시고 테스트 진행 부탁드립니다.

감사합니다.

**Comment by giftset** [comment]
@SoleeChoi 

그렇게 시도해 보았지만 여전히 같은 메세지가 뜨네요.
그리고 다큐멘테이션에 나와 있는대로 ios XCode의 info.plist를 업데이트 했는데,
그렇게 하면 나면 번들 URL을 찾지 못하는 에러가 발생하거나 저희 서버의 데이터를 제대로 받아오지 못하는 경우가 생기는데 혹시 그러한 테스트 케이스가 있었는지 여쭤 봅니다.

**Comment by SoleeChoi** [comment]
1. 혹시 IOS13에서만 해당 증상이 나타나시는건가요?
2. 저희가 제공하는 예제 프로젝트(iamport-react-native/example)은 귀하의 테스트 환경에서 잘 동작하나요?
3. 현재 테스트중이신 프로젝트와 개발 환경을 보다 자세히 안내 부탁드립니다.
- IOS 버전
- Xcode 버전
- RN 버전

info.plist 파일을 업데이트했다고 해서 말씀하신 에러가 발생한 케이스는 없었습니다.

감사합니다.

**Comment by giftset** [comment]
IOS:13.1
Xcode:11.1
RN : 0.60.5 사용중입니다.

**Comment by SoleeChoi** [comment]
react-native-webview 설치 및 링킹이 제대로 됐나요?

**Comment by giftset** [comment]
@SoleeChoi 
네 저희 앱에서 웹뷰 컴퍼넌트만 이용했을 때는 정상적으로 다 작동 잘 되었습니다.
IMP.Payment 컴퍼넌트 사용시에만 문제가 생깁니다.

**Comment by SoleeChoi** [comment]
그렇다면 번거로우시겠지만
프로젝트를 압축해 아임포트 기술지원 메일(support@iamport.kr)로 보내주세요.
디버깅 후 안내해드리겠습니다.

프로젝트 전체 공개가 어려우시면 필요한 부분만 보내주셔도 됩니다.

감사합니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.

이슈가 잘 해결되셨는지 모르겠네요.
귀하께서 올려주신 이슈는, 제가 처음 해결방법을 언급한대로
아임포트 모듈이 내부적으로 사용하고 있는 react-native-webview 모듈의 버전을 7점대 이상으로 올리는 것이 해결 방법이었습니다.

[UIWebVIew는 IOS8 이상부터 WKWebVIew로 대체](https://developer.apple.com/documentation/uikit/uiwebview)되었는데 
IOS12 이하는 warning을 띄웠지만 IOS13부터는 에러를 발생시키는 것으로 파악됩니다.
[react-native-webview 모듈은 7점대 버전부터 UIWebVIew를 없애 이를 해결](https://github.com/react-native-community/react-native-webview/releases/tag/v7.0.1)했습니다.
때문에 아임포트 모듈의 react-native-webview 버전을 7점대 이상으로 올려 버전을 업데이트(v1.3.0) 하였습니다.
주의할 점은 귀하의 프로젝트도 react-native-webview 모듈의 버전을 7점대 이상으로 유지하셔야 한다는 것 입니다.
자세한 내용은 [버전 정보](https://github.com/iamport/iamport-react-native/blob/master/manuals/VERSION.md)를 참고해주세요.

감사합니다.
