### ISSUE TITLE
서드파티 앱에서 본 앱으로 복귀하지 못하는 문제

### ISSUE THREAD

**Issue by ChiwonPark** [iamport/iamport-react-native#36]
안녕하세요, 결제기능 구현 중에 서드파티 앱에서 본 앱으로 복귀 못하는 문제가 발생했습니다.
이런저런 시도를 해보았는데 해결이 되지 않아 도움이 필요해서 글을 남기게 되었습니다.
상세 내용은 아래와 같습니다. 

### 현상
결제는 잘 되고 있으나,  서드파티 결제 앱에서 결제가 완료된 후 본 앱으로 복귀가 안 됩니다.

### 재현 플로우
1)
> 1. 웹뷰 결제화면에서 서드파티앱 실행되는 결제수단 선택
> 2. 서드파티앱 실행
> 3. 다시 본 앱으로 돌아와서 홈버튼
> 4. 다시 서드파티앱으로 돌아가서 결제 진행
> 5. 결제완료시 홈화면(바탕화면)이 보이는 상태

2)
> 1. 카카오톡 실행
> 2. 본 앱에서 카카오페이 선택 후 결제 진행.
> 3. 결제완료시 카카오톡이 보이는 상태

### 시도 해본 것
1. 테스트용으로 간단한 앱을 만들어서 아래 코드를 실행했을 경우 잘 동작하는 것을 확인했습니다.

```
String url ="test_app://";
Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(url));
startActivity(intent);
```

2. 아임포트에서 제공하는 샘플 앱에서도 재현되는 것을 확인했습니다.
모듈버전 v1.2.3 v1.3.0 두 버전 모두 테스트해보았습니다.

### 버전정보
안드로이드 9 Pie
react-native v0.59.8
react-native-webview v5.11.0
iamport-react-native v1.2.3

### 매니페스트
```
<intent-filter>
       <action android:name="android.intent.action.MAIN" />
       <category android:name="android.intent.category.LAUNCHER" />
</intent-filter>
<intent-filter>
       <action android:name="android.intent.action.VIEW" />
       <category android:name="android.intent.category.DEFAULT" />
       <category android:name="android.intent.category.BROWSABLE" />
       <data android:scheme="test_app" />
</intent-filter>
```

### 프로퍼티

```
<View style={{flex: 1}}>
        <IMP.Payment
          userCode={'impxxxxxxx'}
          loading={<Loading />}
          data={data}
          callback={this.callback}
        />
</View>
```

```
const data = {
      pg: pg.pg,
      pay_method: pg.method,
      (... 생략)
      app_scheme: 'test_app',
    };
```

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

현재 말씀하신 바에 의하면

1. 안드로이드에서만 발생하는 문제인가요?
2. 본인 앱 -> 3rd-party 앱 -> 인증 완료 -> 본인 앱 플로우에서는 정상 동작하는데
본인 앱 -> 3rd-party 앱 -> 본인 앱 -> 3rd-party 앱 -> 인증완료 -> 본인 앱 플로우는 동작 안한다는 말씀인가요?
3. 현재 테스트중이신 PG사가 어떻게 되시나요?
4. 현재 테스트중이신 3rd-party앱(결제수단)은 어떤 것인가요?

감사합니다.

**Comment by ChiwonPark** [comment]
답변 감사합니다.

1. 네, 안드로이드에서만 발생하는 것으로 보입니다.
2. 네, 맞습니다.
3. 카카오페이, 모빌리언스 카드 테스트 중입니다.
4. 신한fan, 카카오, 뱅크페이로 테스트 중입니다.

**Comment by SoleeChoi** [comment]
네 해당 내용 재현 후 안내 도와드리겠습니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

확인 결과, 해당 이슈는 안드로이드 OS에서 액티비티 스택에서 발생하는 문제라고 추측됩니다.
본래 안드로이드는 아시다시피 OS상에서 액티비티 스택을 관리하고 
리액트 네이티브는 기본적으로 싱글 액티비티이기 때문에
앱을 이동하면 액티비티 스택에 새 액티비티가 쌓입니다.

즉 처음에는 액티비티 스택에 귀하의 리액트 네이티브 앱의 루트 액티비티(A)만 있다가
외부 앱이 열리게 되면 그 위에 외부 앱의 액티비티(B)가 쌓입니다.
B
A
위와 같은 구조이죠. 모두 포그라운드에 존재합니다.

이후 외부 앱에서 결제 인증이 끝나고 확인 버튼을 누르면 스택에서 외부 앱의 액티비티가 빠지고
남아있던 본래의 앱이 열리게 되는 구조입니다.
A
위와 같은 구조가 됩니다.

하지만 중간에 홈 버튼을 누르거나 개요화면을 누르게 되어 작업을 떠나게 되면
A는 백그라운드에 저장되기 때문에 포그라운드엔 남은 액티비티가 없게 됩니다.
따라서 외부 앱에서 결제 인증이 끝나 액티비티가 소멸되도
다음에 할 작업을 사용자가 직접 선택하지 않는 이상 알 수 없어 발생하는 문제로 생각됩니다.

관련 내용은 안드로이드 공식 문서 [Understand Tasks and Back Stack](https://developer.android.com/guide/components/activities/tasks-and-back-stack)에서 확인해보실 수 있습니다.

감사합니다.

**Comment by ChiwonPark** [comment]
@SoleeChoi 

정리하자면 문의드린 내용은 정상적인 것이고, 
서드파티앱에서 app_scheme으로 저희 앱을 호출함으로써 복귀하는 개념이 아니라 
서드파티앱이 닫히면서 자연스럽게 복귀하는 개념인 것이네요.
답변 감사드립니다.

**Comment by SoleeChoi** [comment]
네 그렇습니다.

IOS의 경우 앱 스킴으로 불러서 앱을 오픈하는 방식이지만
안드로이드는 말씀드린 대로 액티비티 스택이 관리해서 발생하는 이슈로 파악됩니다.

감사합니다!
