### ISSUE TITLE
엑심베이 모듈 연동 요청

### ISSUE THREAD

**Issue by johnwook** [iamport/iamport-react-native#38]
# 배경

- 엑심베이 모듈로 웹 해외 결제 처리 중입니다.
- RN 으로 앱을 빌드하고 있습니다.

# 요청

- 엑심베이건도 지원에 추가가 되었으면 합니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다. 엑심베이 연동여부 검토 후 안내 드리겠습니다. 가능하다고 판단시, 빠르면 다음주 내로 버전업 하도록 하겠습니다. 감사합니다.

**Comment by johnwook** [comment]
> 안녕하세요 아임포트 기술지원팀입니다. 엑심베이 연동여부 검토 후 안내 드리겠습니다. 가능하다고 판단시, 빠르면 다음주 내로 버전업 하도록 하겠습니다. 감사합니다.

빠른 답변 감사드립니다!

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

v1.4.0부터 엑심베이 연동 지원합니다.

감사합니다.
