### ISSUE TITLE
react-native-webview 참조 이슈

### ISSUE THREAD

**Issue by rouge3351** [iamport/iamport-react-native#39]
- version info
react-native : 0.61.5
react-native-webview : 7.4.2
iamport-react-native : 1.4.0

위와 같이 현재 version을 사용하고 있습니다.
현재 저희가 내부 프로젝트에서 사용하고 있는 react-native-webview 와 iamport-react-native 에서 사용하고 있는 library는 같은 버전을 사용하고 있는것으로 확인하였습니다.

하지만 현재 저희가 내부에서 사용하고 있는 WebView를 먼저 import 한 뒤 종료를 하고, IMP.Certificate 를 호출하게 되면 아래와 같은 화면이 나오게 됩니다.
-- Debug Mode 상태
![image](https://user-images.githubusercontent.com/4319422/72727464-5561dc80-3bce-11ea-90a5-1304ddba6cac.png)

-- Debug Mode 해제 상태
![image](https://user-images.githubusercontent.com/4319422/72727218-b63ce500-3bcd-11ea-99ef-d226373da3f7.png)

위와 같은 화면이 나오는 것은 react-native-webview 를 참조할때 생기는 이슈로 보이는데 해결방법이 있을까요 ?

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

말씀해주신 "현재 저희가 내부에서 사용하고 있는 WebView를 먼저 import 한 뒤 종료를 하고, IMP.Certificate 를 호출하게 되면"이 정확히 어떤 말씀일까요?
혹시 IMP.Certification을 호출하고 계시는 코드를 첨부해주시면 이해가 더 빠를 것 같습니다.

참고로 iamport-react-native는
iamport-react-native 모듈이 설치된 앱에 설치된 react-native-webview를 참조하고 있어
앱에는 총 1개(?)의 react-native-webview만 설치됩니다.
즉, iamport-react-native 모듈을 설치한다고 해서 그 모듈이 자기 내부의 react-native-webview를 갖고 있지도 않고 참조하는 것도 아닙니다.

감사합니당.

**Comment by rouge3351** [comment]
저희 전체 앱을 기준으로 봤을때 WebView를 사용하고 있는 곳은 여러군데에 놓여 있는데요,
이때 저희 앱에서 WebView를 한번 render를 한 뒤 아임포트의 IMP.Certificate를 render 하게 되면 다음과 같은 메시지가 나온다는 의미 입니다! :)

**Comment by SoleeChoi** [comment]
그렇군요!
흠 문의주신 내용은 처음이라,
예제 코드에 나와있는 것 처럼 본인인증하기 등의 버튼을 눌렀을때
IMP.Certification을 호출하는 별도의 컴포넌트가 따로 있는 경우

예를 들어,
- A.js에서 본인인증 하기 버튼 클릭
- B.js로 이동
- B.js에서 IMP.certification을 호출

다른 컴포넌트에서 다른 WebView를 호출한다고 하더라도 문제 될 것은 없는뎃
혹시 가능하시다면 관련 부분을 아카이빙 해서
저희 기술지원 이메일(support@iamport.kr)로 보내주시면 직접 디버깅 해보겠습니다!

**Comment by rouge3351** [comment]
말씀하신 부분중에서

- A.js에서 본인인증 하기 버튼 클릭
- B.js로 이동
- B.js에서 IMP.certification을 호출
- A.js로 이동
- C.js로 이동하여 naver.com 을 웹뷰로 로딩하게 될때

위와 같은 에러가 발생하는것으로 저희가 어제 확인 하였습니다.
저희도 어제 디버깅을 하다 보니 iamport-react-native : 1.4.0에서 위와 같은 현상이 있었고,
이후 1.3.0으로 downgrade 하였더니 같은 이슈는 발생하지 않았습니다~!
 
저희 현재 상황이 따로 이부분만 아카이빙만 하기엔 힘든 부분이 있습니다 참조 부탁드리겠습니다

**Comment by SoleeChoi** [comment]
혹시 라우트 라이브러리를 어떤걸 사용하고 계실까요?
[react-navigation](https://github.com/react-navigation/react-navigation)을 사용하시고
B.js의 콜백에서 `navigation.replace` 함수로 라우트 이동을 하고 계시는지
아니면 다른 라이브러리를 사용하고 계시는지 궁금합니다.

저희 쪽에서 설명주신대로 예제 코드를 만들어 디버깅 해보려구요!
감사합니다.

**Comment by rouge3351** [comment]
react-navigation을 사용하고 있고,
IMP.Certification은 react-native의 Modal 하위 컴포넌트로 포함되어있는 상태입니다.!
react-navigation으로 navigation.navigate 함수를 이용하여 C.js 로 이동하고 있습니다!

**Comment by SoleeChoi** [comment]
아마 이미 보셨겠지만 [콜백함수 설정하기](https://github.com/iamport/iamport-react-native/blob/master/manuals/CALLBACK.md)에 보시면
현재와 같은 상황에서 B.js의 콜백에서 C.js 이동시
`navigation.navigate` 대신 `navigation.replace`로 바꿔보시겠어요?
물론 v1.3.0에서는 이슈가 발생하지 않으신다는 점을 볼때 맥락이 맞지 않은 부분이 있지만...

**Comment by rouge3351** [comment]
알수는 없지만 1.3.0을 다시 깔고 이후 uninstall 이후 1.4.0으로 올리게 되니 이전에 있었던 부분은 없어진것으로 확인 했습니다.
아마도 npm package를 깔면서 빌드가 꼬인것이 아닐까 싶네용..

**Comment by SoleeChoi** [comment]
저런 그렇군용...잘 동작하니 다행입니다 :smile:
