### ISSUE TITLE
getAppUrl issue

### ISSUE THREAD

**Issue by ysjoung** [iamport/iamport-react-native#40]
Version info
react-native-cli: 2.0.1
react-native: 0.61.5

위와 같은 버전을 사용하고 있습니다.
카카오페이로 결제를 시도하는 중에 첫화면 에서 '다음'을 누를 시 IOS에서는 카카오페이 결제화면으로 넘어가는데 Android에서는 callBack을 호출하고있습니다.

response에 에러 메세지로 Cannot read property 'getAppUrl' of undefined와 같이 받고 있습니다

params : 
{
    amount: 5000
    app_scheme: "@@@@"
    buyer_email: "dustn1524@naver.com"
    buyer_tel: "01030327602"
    deduct_from_balance: 0
    escrow: false
    m_redirect_url: "http://localhost/iamport"
    merchant_uid: "@@@@@"
    name: "@@@@"
    pay_method: "card"
    pg: "kakaopay"
    profile_uuid: undefined
}

--소스코드--
<IMP.Payment
          userCode={impId}
          loading={<Video source={require('../assets/images/loading_1.mp4')} style={styles.backgroundVideo} />} 
          data={params}             // 결제 데이터
          callback={response => this._callback(response)}
          style={styles.webview}
        />

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

안드로이드에서 카카오페이 결제 시,
카카오페이 결제 화면에서 `다음` 버튼을 눌러도
다음 단계로 진행되지 않고 바로 콜백이 실행되면서
`Cannot read property 'getAppUrl' of undefined`라는 오류 메시지를 받게 된다는 말씀이시죠?

관련 내용 확인 후 오늘 중으로 안내 드리겠습니다.

감사합니다.

**Comment by SoleeChoi** [comment]
음 일단 저희쪽에서는 정상동작하는데,
저 메시지는 NativeModules에 선언된 Iampor 모듈이 undefined 라는 말이니까
iamport-react-native 모듈이 android 네이티브 단에 링킹이 제대로 안된 것 같거든요?
혹시 제대로 링킹되었는지 확인가능하실까요?

[설치하기 - 안드로이드](https://github.com/iamport/iamport-react-native/blob/master/manuals/INSTALL.md#%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C) 매뉴얼을 보시면, 수동 링킹하는 방법이 나와있는데
링킹이 제대로 되었으면 이 과정이 필요없거든요.

감사합니다.

**Comment by ysjoung** [comment]
링킹문제가 맞았습니다.
감사합니다.

**Comment by Mineru98** [comment]
혹시 expo 환경에서 eject하지 않고 안드로이드 스튜디오 없이 개발을 하고 있는데 링킹을 해줘야 위와 같은 오류 없이 제대로 작동하나요?

**Comment by SoleeChoi** [comment]
@Mineru98 

안녕하세요 아임포트 기술지원팀입니다.

eject는 외부 앱(카드사 앱, 간편결제 앱 등)으로의 이동을 위해
웹뷰의 URL을 앱 URL로 변환하기 위해 네이티브 코드가 필요한 경우를 대비한 것으로
모빌리언스 - 휴대폰 소액결제만 사용하시는 경우
외부 앱으로의 이동 과정 없이 결제 가능하시기 때문에 eject하지 않으셔도 됩니다.
해서 저번에 귀하께서 아직 eject하지 않으셨다고 하셨을때 따로 언급하지 않았습니다.

이용에 참고 부탁드립니다.
감사합니다.

**Comment by Mineru98** [comment]
다른 외부 앱으로 이동을 하고 싶다면 eject이 필수인게 맞나요?

**Comment by SoleeChoi** [comment]
@Mineru98 

네 그렇습니다.
