### ISSUE TITLE
pg 속성을 이용한 복수 PG사 기능 추가요청

### ISSUE THREAD

**Issue by cshyeon** [iamport/iamport-react-native#41]
https://docs.iamport.kr/tech/pg-parameter 문서를 참조하여
data.pg 값을 "{ pg사 코드값 }.{ pg사 상점아이디 }" (eg. "kakaopay.cid1234")로 설정하여 결제테스트를 해보았는데, 현재 사용이 불가능한것으로 보입니다.

`PaymentWebView` 컴포넌트에서 data.pg 속성이 propTypes로 제한되어 발생한 문제인걸로 추측됩니다.
```javascript
PaymentWebView.propTypes = {
  userCode: PropTypes.string.isRequired,
  data: PropTypes.shape({
    pg: PropTypes.oneOf(PG),
...
```

향후 업데이트에 반영되었으면 합니다!

**Comment by SoleeChoi** [comment]
네 맞습니다 ㅠㅠ
다음 버전 업데이트 반영하도록 하겠습니다!
감사합니다!

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

iamport-react-native 새 버전(v1.4.1) 업데이트때
말씀해주신 사항이 반영되었습니다.

버전정보: https://github.com/iamport/iamport-react-native/blob/master/manuals/VERSION.md

더 나은 모듈 개발에 도움을 주셔서 감사합니다.
