### ISSUE TITLE
Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening AwesomeProject.xcworkspace.

### ISSUE THREAD

**Issue by pyeonjaesik** [iamport/iamport-react-native#42]
이런 오류가 뜨네요...

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

어떤 단계에서 저런 오류가 뜨셨는지가 궁금합니다.
AwesomeProject라는 테스트 프로젝트를 빌드하시려고 하시는 것 같은데,
저 메시지만 봐서는 아임포트 모듈에서 어떤 에러가 발생했는지 알기가 어려워서요.

- XCode 버전
- 테스트 기기 종류와 IOS 버전
- 테스트 과정

위 3가지 사항에 대해 보다 상세한 안내 부탁드립니다.
감사합니다.

**Comment by SoleeChoi** [comment]
https://github.com/facebook/react-native/issues/25240

관련 에러 내용 검색 결과 위 링크를 참조하시면 도움이 되실 것 같습니다.
