### ISSUE TITLE
페이코 결제 관련 이슈

### ISSUE THREAD

**Issue by SOOJEONG1** [iamport/iamport-react-native#43]
페이코 앱이 실행되고 '앱으로 결제'를 클릭하면 '결제시 에러가 발생했습니다' 라는 문구가 출력되며
결제가 진행되지 않습니다 (결제 창이 출력되지 않습니다).
이 경우, 에러메세지는 아래와 같이 확인되고 있습니다. 확인부탁드립니다. 감사합니다!

'VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc.', { dt: 571, prevDt: 2946, contentLength: 4125 }

Connection to daemon was invalidated

[ProcessSuspension] 0x2834b6e00 - WKProcessAssertionBackgroundTaskManager: Ignored request to start a new background task because the application is already in the background

Can't end BackgroundTask: no background task exists with identifier 4 (0x4), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug

[Snapshotting] Snapshotting a view (0x1071ff000, UIKeyboardImpl) that is not in a visible window requires afterScreenUpdates:YES.

**Comment by SoleeChoi** [comment]
안녕하세요.

기술지원문의 이메일 문답을 통해 관련 이슈가 해결되어 closed 처리합니다.
감사합니다.
