### ISSUE TITLE
WebView 중복 사용시 "Invariant Violation: Tried to register two views with the same name RNCWebView" 에러

### ISSUE THREAD

**Issue by KYEBOKWAK** [iamport/iamport-react-native#48]
안녕하세요. 

웹뷰 중복 사용시 같은 이름의 웹뷰가 두개 사용 되고 있다는 에러가 납니다.

에러 발생 예시:
하나의 웹뷰는 iamport-react-native
다른 웹뷰는 react-native-webview 사용
두개의 웹뷰는 서로 다른 View 에 랜더함.

<img width="392" alt="스크린샷 2020-03-17 오후 9 38 01" src="https://user-images.githubusercontent.com/40347000/76856927-b5f05b80-6897-11ea-9538-3369f281070a.png">

iamport-react-native 의 node_modules 에 포함되어 있는 react-native-webview를 제거하니 정상 동작 합니다.
해결 이슈 참고: https://github.com/react-native-community/react-native-webview/issues/373#issuecomment-520141870

**Comment by jangbora** [comment]
아임포트기능 이외의 부분에서 WebView 사용을 위해 프로젝트의 package.json 의 dependecy 에 react-native-webview 를 별도로 명시해두신 것 같습니다. 때문에 iamport-react-native 에서 참조하는 react-native-webview 와 서로 다른 버전이 2개 설치된게 아닌가 싶습니다. (https://github.com/iamport/iamport-react-native/blob/master/package.json#L19)

package.json 에 명시하신 react-native-webview 의 버전정보를 알 수 있을까요?

**Comment by KYEBOKWAK** [comment]
답변이 너무 늦어 죄송합니다. 
package.json 명시 webview 버전 : 8.1.2

서로 다른 버전이 2개 설치 된게 맞습니다.

그래서
기존 iamport 1.4.0 ver 에 명시된 버전 webview (7.4.2) 으로 
react-native-webview@7.4.2 로 설치 후 node_module 삭제 후 재빌드 하면
동작하다가 안하다가 합니다.

그래서 우선 react-native-webview를 최신버전으로 유지하고
iamport에 포함된 webview를 지우고 빌드 했습니다.

(https://github.com/iamport/iamport-react-native/blob/master/package.json#L19)
해당 명시로 변경하니, 지우지 않아도 정상동작 하는걸 확인 했습니다.
package.json 버전 명시 관련하여 하나 더 배웠습니다. 감사합니다.

헌데 아직 npm 설치시 1.4.0 버전이 설치 되고 있습니다.
해당 부분 업데이트 부탁드립니다.

대응해주셔서 너무 감사합니다.

**Comment by jangbora** [comment]
아임포트 플러그인 v1.4.1 로 업데이트(npm publish)하였습니다. 
저희가 파악하기로는, iamport-react-native 가 필요로하는 react-native-webview 의 7.4.2 버전 미만의 것이 이미 @KYEBOKWAK 님의 프로젝트에 설치가 되어있으면, iamport-react-native 설치 시 iamport-react-native 밑에 node_modules/react-native-webview 가 별도 설치되는 것으로 확인됩니다. 

이 때문에 node_modules/react-native-webview 와 node_modules/iamport-react-native/node_modules/react-native-webview 가 공존하면서 충돌하게 되었던 것 같습니다. 

iamport-react-native 의 package.json 에 peerDependency를 보다 명확히 정의하여 이런 경우를 대비하였습니다.
