### ISSUE TITLE
IMP.Payment에서 Loading 후 결제 클릭 안됩니다.

### ISSUE THREAD

**Issue by Mineru98** [iamport/iamport-react-native#50]
결제 기본 값 입력 후에 결제 진행을 하면 Loading 컴포넌트가 올라온 뒤에 결제 동의 화면이 올라오는데, 
Loading 컴포넌트가 사라지지 않고 [Loading zIndex 값](https://github.com/iamport/iamport-react-native/blob/master/src/styles.js#L14)과  [WebView zIndex 값](https://github.com/iamport/iamport-react-native/blob/master/src/styles.js#L18)이 제대로 적용이 안되는것 같습니다.
그래서 결제 WebView가 로딩이 되어도 Loading 컴포넌트가 화면을 차지 하고 있어서 결제 진행을 할 수 없는 상태가 됩니다...

해당 오류가 해결 된 버전을 릴리즈 해주셨으면 합니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

v1.4.0에서 v1.4.2로 올리는 과정에서 생긴 버그로
오늘 중으로 수정된 v1.4.3를 배포할 예정입니다.

참고로 해당 버그는 iframe 방식 PG사(다날, 페이코, 모빌리언스 - 휴대폰 소액결제, 스마일페이, 이니시스 - 빌링결제)의 경우에만 발생합니다.

이용에 불편을 드려 죄송합니다.

감사합니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

말씀하신 버그가 수정된 새 버전 v1.4.4가 업데이트 되었습니다.
확인 부탁드립니다.

감사합니다.

**Comment by Mineru98** [comment]
v1.4.4 을 확인해 보았는데요. 해당 문제가 여전히 존재하고 있습니다.
[setShowLoading(true)](https://github.com/iamport/iamport-react-native/blob/master/src/components/Payment/PaymentWebView.js#L77) 코드가 제대로 적용이 안되기 때문에 일어나고 있는 문제로 보이는데 this.xdm.injectJavaScript로 js 코드 주입 후 결제 화면 로드가 되는 시점을 제대로 잡을 순 없는지 궁금합니다.

만약 로드 시점을 제대로 잡을 수 없다면 해당 문제를 계속 안고 가야할까요?

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

해당 문제라고 하시면 "결제 WebView가 로딩이 되어도 Loading 컴포넌트가 화면을 차지 하고 있어서 결제 진행을 할 수 없는 상태"를 말씀하시는건가요?
(즉 로딩 컴포넌트가 웹뷰 컴포넌트를 가리고 있다든가, 로딩 컴포넌트가 웹뷰 컴포넌트가 합쳐져 있다든가 하는 v1.4.2의 버그)

테스트중이신 단말, 가맹점 식별코드, PG사 및 결제수단이 어떻게 되실까요?

버전 업데이트 후 새 앱을 만들어 확인했을때 안드로이드와 IOS 환경에서 웬만한 결제수단에 대해 정상 동작하는 것을 확인했는데,
혹시 이전 버전에 대한 캐시 등이 남아있을 수 있느니, unlinking -> uninstall -> reinstall -> relinking 해보셔도 같은 문제가 지속되시는지 알 수 있을까요?

감사합니다.

**Comment by Mineru98** [comment]
저의 개발 환경은 일단 expo에서 eject를 하지 않은 상태이고, 말하신대로  캐시 문제일지도 몰라서 npm 모듈 전체를 아예 다시 지우고 node_modules 파일도 지우고 다시 설치를 진행을 해봤는데요. 여전히 문제가 발생은 합니다.

테스트 중인 가맹점 식별코드는 imp75769545이며, PG사는 KG 모빌리언스입니다.
아래 사진이 참고가 될진 모르겠지만 해주세요.
![참고 이미지](https://i.ibb.co/p4RqxPQ/image.png)

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

- expo init: expo-cli v3.19.2, expo SDK v37.0.3 환경에서 새 앱을 만들고
- npm install iamport-react-native: v1.4.4
- npm install react-native-webview: v9.3.0 설치후
- react-native link iamport-react-native
- react-native link react-native-webview 후

귀하께서 말씀하신 가맹점 식별코드 imp75769545로 테스트 해 본 결과
KG이니시스 창이 떠서(아마 KG모빌리언스 계약이 되지 않아 기본 PG인 KG이니시스 창이 뜨는 것으로 추정)
저희 쪽 가맹점 식별코드로 다시 테스트 해봤는데
IOS 안드로이드 모두 정상적으로 결제창이 호출되는 것을 확인했습니다.

혹시 가능하시다면 프로젝트를 압축해서 기술지원 이메일 support@iamport.kr로 보내주실 수 있으신가요?
직접 디버깅 해보려고 합니다.
프로젝트 전체 공개가 부담스러우시다면, 결제창 호출 부분만 떼서 압축하셔도 됩니다.

감사합니다.

**Comment by Mineru98** [comment]
제가 react-native-webview 버전을 7.4.0 이상이라고 해서 7.4.0으로 맞춰두고 테스트를 진행해서인지 제대로 작동이 안되었던것 같습니다. 감사합니다
