### ISSUE TITLE
SvcId[서비스아이디] 확인 요망

### ISSUE THREAD

**Issue by Mineru98** [iamport/iamport-react-native#52]
아래 사진처럼 SvcId[서비스아이디] 확인 요망이란 에러가 뜨는데, 어떤 경우에 뜨는 에러인지 모르겠습니다.
![이미지](https://i.ibb.co/fMcPNzG/2.png)

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

결제창 화면을 보니, KG모빌리언스 휴대폰 소액결제를 테스트 중이신 것 같은데
KG모빌리언스의 경우에는 공식적으로 제공되는 테스트 계정이 없어 
KG모빌리언스와 계약 후 직접 테스트 계정을 받아서 테스트해주셔야 하는 단점이 있습니다.

즉, 아임포트 관리자 페이지에 KG모빌리언스 - 휴대폰 소액결제를 테스트 모드로 설정하셔도
테스트가 불가능합니다.

이용에 불편을 드려 죄송합니다.

감사합니다.
