### ISSUE TITLE
react native 에서 발생하는 오류 . 

### ISSUE THREAD

**Issue by andy-eincloud** [iamport/iamport-react-native#53]
리액트 네이티브에서 본인인증을 위해 아임포트를 붙여보는 중입니다. 

본인인증 진행을 위해 ,  아임포트의 예시 코드를 가지고 시도를 해보는 중인데 아래 처럼 오류가 발생하는데요, 

혹시 참고할만한 정보가 있을까요? 

1. 오류 화면. 

![image](https://user-images.githubusercontent.com/64706556/81783730-bb37f280-9536-11ea-8eda-578ebb1fdc42.png)

2. 사용한 코드 ( 예제로 올려져 있는 코드 )

의견 부탁드립니다. 

`
import React from 'react';

/* 아임포트 모듈을 불러옵니다. */
import IMP from 'iamport-react-native';
/* 로딩 컴포넌트를 불러옵니다. */
import Loading from './Loading';

export function Certification({ navigation }) {
  /* [필수입력] 본인인증 종료 후, 라우터를 변경하고 결과를 전달합니다. */
  function callback(response) {
    navigation.replace('CertificationResult', response);
  }

  /* [필수입력] 본인인증에 필요한 데이터를 입력합니다. */
  const data = {
    merchant_uid: `mid_${new Date().getTime()}`,
    company: '아임포트',
    carrier: 'SKT',
    name: '홍길동',
    phone: '01012341234',
    min_age: '',
  };

  return (
    <IMP.Certification
      userCode={'iamport'}    // 가맹점 식별코드
      loading={<Loading />}   // 웹뷰 로딩 컴포넌트
      data={data}             // 본인인증 데이터
      callback={callback}     // 본인인증 종료 후 콜백
    />
  );
}

export default Certification;`

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

이메일 문의로 안내를 마쳐 해당 이슈는 close 하도록 하겠습니다.

감사합니다.
