### ISSUE TITLE
프로젝트 폴더 구조가 매뉴얼과 차이가 있습니다.

### ISSUE THREAD

**Issue by dreamer-ahn** [iamport/iamport-react-native#57]
expo37에서 아임포트를 연동하려 합니다. 

그래서 진행중인데 프로젝트 폴더 구조가 매뉴얼과 차이가 있습니다.
expo eject 실행 후에 ios 디렉토리 안에 Libraries도 존재하지 않고, info.plist파일의 위치도 [프로젝트 폴더]/ios/[프로젝트 이름]/info.plist가 아닌 [프로젝트 폴더]/ios/[프로젝트 이름]/Supporting/info.plist에 존재합니다.
<img width="271" alt="스크린샷 2020-07-11 오후 11 38 05" src="https://user-images.githubusercontent.com/19203523/87226568-9691b700-c3cf-11ea-9d93-d673a1d1b3e8.png">

임의로 ios/Libraries생성 libIamportReactNative.a, libRNCWebView.a 추가 후 5.설정하기
를 진행 후 run을 하면  아래와 같이 애러가 발생합니다.
![스크린샷 2020-07-12 오전 12 51 58](https://user-images.githubusercontent.com/19203523/87228090-e5dce500-c3d9-11ea-8e1c-c0668853297b.png)

여러번 시도해도 계속 같은에러 발생됩니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

현재 보고계신 매뉴얼은 expo SDK 35 미만에서 ExpoKit 기반으로 eject 하는 방법에 대해 기재하고 있어
폴더 구조에 차이가 있는 것으로 생각됩니다.

아래에 expo SDK 35 이상 대상
bare workflow 방식으로 eject하여 아임포트를 연동하는 방법을 안내해 놓았으니 참고 부탁드립니다.
https://github.com/iamport/iamport-react-native/issues/51

참고로 eject에 성공하면 libIamportReactNative.a, libRNCWebView.a와 같은 파일은
귀하의 프로젝트에 자동으로 추가되는 것이라
지금처럼 강제로 추가하지 않으셔도 됩니다.

감사합니다.
