### ISSUE TITLE
웹뷰 최신 버전 10점대에서 제대로 동작하지 않습니다!

### ISSUE THREAD

**Issue by nab5m** [iamport/iamport-react-native#62]
TypeError: undefined is not an object (evaluating '_this.xdm = xdm')

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

"웹뷰 최신 버전 10점대"라고 하셨는데, [react-native-webview](https://github.com/react-native-community/react-native-webview)의 버전을 말씀하시는 건가요?

아래 정보를 알려주시면 보다 빠르게 확인이 가능할 것 같습니다.

- iamport-react-native 버전
- react-native-webview 버전
- 테스트 환경: 아이폰(아이폰 버전) / 안드로이드(안드로이드 버전)
- 테스트 기기 종류: EX. 갤럭시 S10, 아이폰 11 등

감사합니다.
