### ISSUE TITLE
가상계좌시 계좌번호를 알 수 있는 방법이 없나요??

### ISSUE THREAD

**Issue by KYEBOKWAK** [iamport/iamport-react-native#63]
안녕하세요.

가상계좌 시도시 콜백으로 가상계좌번호가 넘어오지 않아서,

API로 조회 할 수 있는 방법을 찾아보는데,

없는거 같아서 질문 남깁니다.

감사합니다!

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

콜백으로는 최소한의 결제 정보(imp_uid, merchant_uid)가 넘어오는데요,
이를 가맹점 웹서버로 전달해, 아임포트 결제 내역을 조회([GET /payments/{imp_uid}](GET /payments/{imp_uid}))해보시면
응답 결과에 발급 된 가상계좌 정보를 아래와 같이 받아보실 수 있습니다.

- vbank_code (string, optional): 가상계좌 은행 표준코드 - (금융결제원기준)
- vbank_name (string, optional): 입금받을 가상계좌 은행명
- vbank_num (string, optional): 입금받을 가상계좌 계좌번호
- vbank_holder (string, optional): 입금받을 가상계좌 예금주
- vbank_date (integer, optional): 입금받을 가상계좌 마감기한 UNIX timestamp
- vbank_issued_at (integer, optional): 가상계좌 생성 시각 UNIX timestamp 

참고로 아임포트 API를 호출할때는 사용자 인증을 위해 먼저 액세스 토큰을 발급([POST /users/getToken](POST /users/getToken))받은 후,
발급 받은 액세스 토큰을 매 API 호출시마다 리퀘스트 헤더에 실어 보내야 하는데요,
액세스 토큰을 발급 받을 때 아임포트 관리자페이지 > 내정보에 설정된 REST API키, REST API Secret값을 요청 본문으로 보내게 됩니다.
즉 이 두 값이 노출되면 누구나 귀하의 가맹점 정보로 액세스 토큰을 발급 받을 수 있고,
이 액세스 토큰으로 아임포트 API를 호출해볼 수 있으니 결제내역을 조회해볼수도 있고 승인된 결제내역을 취소할수도 있습니다.
따라서 이 두 값은 외부로 절대로 노출되서는 안되기 때문에 아임포트 API는 반드시 가맹점 웹서버에서 호출해야합니다.
프론트 영역에서 아임포트 API를 호출하면 CORS 에러가 발생합니다.

물론 모바일 앱에서는 결제창을 웹뷰로 띄우기 때문에 웹 브라우저는 달라서 CORS에러가 나지는 않겠으나
향후 빌드된 APK 파일이나 IPA파일이 노출되었을때 REST API키과 REST API Secret값도 함께 노출될 수 있으니
아임포트 REST API는 가맹점 웹서버에서 호출해주시길 바랍니다.

감사합니다.

**Comment by KYEBOKWAK** [comment]
답변 감사합니다.
https://api.iamport.kr/#/
해당 api 호출기로 조회하면

{
  "code": -1,
  "message": "존재하지 않는 결제정보입니다.",
  "response": null
}
존재하지 않는 결제정보라고 나옵니다.

imp_uid : imp_211167211427 
입니다.

관리자 페이지에선 계좌를 발급 받은 상태입니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

해당 결제건(`imp_211167211427`)이 결제할때 보내신 userCode(가맹점 식별코드)는 `imp75897735`로
이와 연결된 아임포트 관리자페이지 계정은 `bogame@naver.com`로 확인됩니다.
그런데 API 조회를 위해 액세스 토큰 발급시 요청 본문으로 보낸 REST API키과 REST API Secret값은
해당 계정의 것이 아닌 것으로 확인됩니다.

아임포트 관리자페이지에 bogame@naver.com로 로그인하신 후
내정보에 설정되어 있는 REST API키과 REST API Secret으로 다시 액세스 토큰을 발급 받으신 후
다시 조회해보시길 바랍니다.

감사합니다.

**Comment by KYEBOKWAK** [comment]
확인 했습니다. 감사합니다.
api, secret 키를 잘못입력햇네요ㅜ ;

답변 감사합니다!
