### ISSUE TITLE
아임포트 모듈 

### ISSUE THREAD

**Issue by choirim** [iamport/iamport-react-native#65]
안녕하세요.
아임포트 모듈
<IMP.Payment
       userCode={'식별코드'} 
       data={data} 
       callback={callback} />
를 사용중에 있습니다.

앱을 들어가서 처음 결제 할때 결제 하고나서 다시 앱으로 돌아오면 
결제는 되어있는데 

Error loading page
Domain::undefined
Error Code: -10
Description net::ERR_UNKNOWN_URL_SCHEME

라는 오류가 있는 페이지가 뜹니다.
그리고 다음 결제 부터는 결제 후 돌아오는 아임포트 화면이 정상적으로 잘 나옵니다.
얼마전만해도 오류 없이 결제가 잘 되었는데 저 오류가 저희쪽 문제인지 아임포트 모듈 문제인지 모르겠어서 이슈에 올립니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

해당 오류를 겪으신 결제건의 imp_uid를 전달해주시면 로그 확인해보도록 하겠습니다.

감사합니다.

**Comment by choirim** [comment]
imp_161524646195
입니다
확인 부탁드립니다~

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

저희쪽에서 테스트 해본 결과로는 정상 동작해서, 재현이 안되서 몇가지만 더 질문드리도록 하겠습니다.

- 앱을 처음 열고 첫 결제 시도했을때만 해당 현상이 "항상" 재현되는 것일까요?
- 보내주신 imp_uid로 로그를 확인해 본 결과, 안드로이드에서 테스트 하신 결제건인데, IOS에서도 동일한 증상이 재현되시나요?
- 사용하고 계신 iamport-react-native 모듈의 버전은 어떻게 되나요?
- 말씀해주신 에러 화면이 나올때 안드로이드 스튜디오 등에서 찍히는 로그는 없나요?

감사합니다.

**Comment by 0strich** [comment]
q. 앱을 처음 열고 첫 결제 시도했을때만 해당 현상이 "항상" 재현되는 것일까요?
a. 넵 앱 열고 첫 결제 시도시 항상 나오고 있습니다 (에러화면 나오고 결제는 정상처리 됩니다)

q. 보내주신 imp_uid로 로그를 확인해 본 결과, 안드로이드에서 테스트 하신 결제건인데, IOS에서도 동일한 증상이 재현되시나요?
a. 현재 저희가 안드로이드만 출시 예정이기 때문에 iOS는 테스트가 불가능한 상황입니다~

q. 사용하고 계신 iamport-react-native 모듈의 버전은 어떻게 되나요?
a. 기존에 사용하던 버전은 1.5.1이고, 최신 버전(1.5.2)으로 업데이트 하고 결제해도 동일한 현상이 나타납니다

q. 말씀해주신 에러 화면이 나올때 안드로이드 스튜디오 등에서 찍히는 로그는 없나요?
a. 로그는 아무것도 안찍힙니다


시간내주셔서 감사합니다~ ^^

**Comment by 0strich** [comment]
![스크린샷 2020-09-16 오후 4 35 20](https://user-images.githubusercontent.com/33608588/93306324-a8159600-f83a-11ea-8c49-c1e9ae496cf2.png)

ISP 인증요청 버튼을 클릭했을 떄 다음과 같이 에러가 나옵니다~

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

해당 이슈와는 관련이 없을지도 모르지만, 나이스페이 모바일 결제 환경 신 모듈을 제공하고 있는데
이를 적용하려면 결제 데이터를 보낼때 niceMobileV2 파라메터를 true로 보내야 합니다.
아래와 같이 해보시고도 증상이 반복되신다면 저희가 디버깅 가능한 프로젝트를 압축하여
support@iamport.kr로 보내주시면 감사하겠습니다.

```javascript
<IMP.Payment
  data={{
    // 나머지 결제 데이터
    niceMobileV2: true
  }}
/>
```

감사합니다.

**Comment by 0strich** [comment]
소스코드 문제 확인했습니다!! 감사합니다~

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

혹시 무엇이 문제였는지 공유 가능하실까요?
차후 같은 이슈를 겪고 계신 고객이 있다면 안내드리는데 참고할 수 있을 것 같습니다.

감사합니다.

**Comment by 0strich** [comment]
재확인해보니 아직 해결 되지 않아서 다시 문의드립니다..

앱 실행 후, 첫 결제 실패시에 로그에 다음과같이 찍히고 위에 올려드린 스크린샷과 동일한 화면이 출력 됩니다~

Encountered an error loading page {"canGoBack": true, "canGoForward": false, "code": -10, "description": "net::ERR_UNKNOWN_URL_SCHEME", "loading": false, "target": 2333, "title": "웹페이지를 사용할 수 없음", "url": "intent://TID=nictest00m01012009181126237687#Intent;scheme=ispmobile;package=kvp.jjy.MispAndroid320;end"}

확인해 주시면 갑사하겠습니다~

**Comment by coffee764** [comment]
저도 해당 문제가 재현됩니다

**Comment by SoleeChoi** [comment]
@coffee764 

안녕하세요 아임포트 기술지원팀입니다.

iamport-react-native 모듈은 `react-native-webview`에 dependent한데
`react-native-webview`의 버전 10.8.3 이상부터 해당 문제가 발생하고 있는 것 같습니다.

일단은 react-native-webview의 버전을 10.8.2이하로 낮춰서 사용하시길 바랍니다.
(10.8.2까지는 정상 동작하는 것을 확인함)

저희쪽에서 10.8.3 이상 버전에서도 정상 동작하도록 코드를 수정하거나
`react-native-webview`의 자체 로직 문제라고 파악될 경우 수정해 PR을 날려야할 것 같은데
아무래도 시간이 다소 소요될 것으로 생각되기 때문입니다.

이후 업데이트 된 상황이 생길시 안내드리도록 하겠습니다.
감사합니다.

**Comment by 0strich** [comment]
@SoleeChoi 
안녕하세요~ 답변주셔서 감사합니다~
저희는 기존에 10.2.3 버전을 사용했을 때부터 해당 에러가 나오는 걸로 확인이 되고 있습니다
10.8.0 ~ 10.8.2 버전으로 업그레이드 하고 시도를 해봤지만 동일한 내용이 나오는 것 같습니다~

혹시 해당 현상이 나오지 않는 부분을 테스트하신 부분이 있다면 공유 받아 볼 수 있을까요??

감사합니다~

**Comment by 0strich** [comment]
package.json react-native-webview 에서 캐럿(^)을 빼고 npm install 했더니 정상 작동 하는것 같습니다~
감사합니다~

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

`react-native-webview` 10.8.3 이상 버전에서도 정상적으로 동작하도록 코드를 추가하였습니다.
해당 코드가 반영된 `iamport-react-native` 새로운 버전을 패치하고자 하였으나
기존 사용자와의 레거시를 위해 일단 급한대로 `feature/react-native-webview` 브랜치에 반영하였습니다.

`react-native-webview` 10.8.3 이상 버전을 사용하고자 하신다면,
아래 명령어를 통해 `feature/react-native-webview` 브랜치를 설치하시길 바랍니다.

`bash
$ npm install --save npm install --save https://github.com/iamport/iamport-react-native\#feature/react-native-webview
`

향후 해당 코드의 안정성이 검증될 경우, `iamport-react-native` 새 버전에 반영하도록 하겠습니다.
감사합니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

`feature/react-native-webview` 브랜치는 [v1.6.0](https://github.com/iamport/iamport-react-native/tree/v1.6.0)에 반영되었습니다.

감사합니다.

**Comment by yjb94** [comment]
@SoleeChoi 해당 현상 react-native-webview 10.9.2에서도 확인됐는데 재현되시나요?

**Comment by yjb94** [comment]
@SoleeChoi 해당문제 v1.6.0 이상에서 재현됐습니다. 확인 부탁드립니다.
```
Error loading page
Domain::undefined
Error Code: -6
Description net::ERR_CONNECTION_REFUSED
````
iamport-react-native: v1.6.3
react-native-webview: v10.9.2

**Comment by SoleeChoi** [comment]
@yjb94 안녕하세요 아임포트 기술지원팀입니다.

3일전에 댓글 남겨주셨다는게 메일로 전달됐는데 아무리 찾아도 댓글이 없어서 답변을 드리지 못했습니다 ㅠㅠ
저희가 말씀하신 같은 환경에서 테스트 해봤는데 재현이 안되어서...
혹시 테스트 중이신 PG사와 카드사 알 수 있을까요?

감사합니다.

**Comment by yjb94** [comment]
@SoleeChoi 답변 감사합니당.

안드로이드 환경에서만 재현이 되었고
PG사는 `eximbay`이고 카드사는 테스트 환경에서 진행해서 특정되지 않습니당

**Comment by yjb94** [comment]
> PaymentWebView

넵 해당 코드 삽입되어있습니다

**Comment by yjb94** [comment]
> 안녕하세요 아임포트 기술지원팀입니다.
> 
> 그럼 혹시 재현되는 프로젝트를 압축해 아임포트 기술지원팀 이메일([support@iamport.kr](mailto:support@iamport.kr))로 보내주실 수 있으실까요?
> 정확한 원인을 직접 디버깅을 통해 찾아봐야할 것 같습니다.
> 참고로 용량 이슈가 생길 수 있으니 node_modules는 모두 지우신채로 압축 부탁드립니다.
> 
> 감사합니다.

@SoleeChoi 프로젝트를 보내드리기 어려울 것 같아서 추가 정보와 함께 아임포트 모듈 수정시에 처리 된 내용 공유드립니다.

### 추가정보

1. 안드로이드 환경에서만 재현됩니다.
2. 리액트 네이티브 디버그 모드에선 재현되지 않는 것 같습니다.
2. 외부 앱으로 라우팅 되는 경우가 아닌, 웹뷰로 결제가 진행됩니다.
3. PG사 eximbay, 결제 웹뷰 실행 - 결제 내용 입력(샌드박스값) - 결제 완료 - 해당 에러메시지와 함께 결제 성공

### 모듈 수정 내용
```
 function onShouldStartLoadWithRequest(request) {
    const { url, lockIdentifier } = request;
    const iamportUrl = new IamportUrl(url);
    
    if (lockIdentifier === 0 /* && react-native-webview 버전이 v10.8.3 이상 */) {
      /**
       * [feature/react-native-webview] 웹뷰 첫 렌더링시 lockIdentifier === 0
       * 이때 무조건 onShouldStartLoadWithRequest를 true 처리하기 때문에
       * Error Loading Page 에러가 발생하므로
       * 강제로 lockIdentifier를 1로 변환시키도록 아래 네이티브 코드 호출
       */
      RNCWebView.onShouldStartLoadWithRequestCallback(false, lockIdentifier);
    }

    if (iamportUrl.isAppUrl()) {
      /* 3rd-party 앱 오픈 */
      open3rdPartyApp(iamportUrl);
      return false;
    }
    if (iamportUrl.isPaymentOver()) {
      callback(iamportUrl.getQuery());
      return false;
    }
    if (isWebViewLoaded && showLoading && iamportUrl.isIframeLoaded()) {
      /**
       * only for IOS
       * iframe이 load되면(url이 about:blank 또는 https://service.iamport.kr이 아니면)
       * webview의 loading 상태를 해제한다
       */
      setShowLoading(false);
    }
    return true;
  }
```
앱 URL이 아닌 경우에도 동작되는 것으로 보아, `isAppUrl()`로 분기 되어있는 코드를 밖에서 처리하도록 하였습니다.
해당 코드 삽입시에 아임포트 내부적으로 어떤 문제가 생길 지 모르겠어서 확인 부탁드립니다.

감사합니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

1.
일단 엑심베이로 외부 앱 이동 없이 결제를 진행하려면 해외에서 발급 받은 카드만 가능한 것 같습니다.
저희가 갖고 있는 카드가 해외에서 발급 받은 카드는 없어서(VISA 등 여부와는 별개) 카드 번호를 입력하면 바로 국내 결제 화면으로 전환이 되어서요.
혹시 다른 PG사도 테스트 하고 계신 것이 있으실까요?

2.
리액트 네이티브 디버그 모드에선 재현되지 않는다는 말씀이
react-native cli나 안드로이드 스튜디오에서 Run해서 설치된 앱에서는 재현이 안되시고
apk 파일을 만든 후 해당 apk 파일을 설치해서 테스트 했을때만 재현된다는 말씀이신가요?

3.
저희가 1번과 같은 이유로 정확한 디버깅은 안되는 상태인데
혹시 iamport-react-native 모듈 코드를 수정하신 이유가 있으실까요?
특별히 없으시면 원래 모듈이 제공하는 원본 소스대로 롤백하신 후 시도해보셔도 이슈가 재현되실까요?

감사합니다.

**Comment by yjb94** [comment]
@SoleeChoi 
1. 현재 eximbay에서 결제는 test merchant로 사용하고 있습니다. 현재 자사에서는 테스트 계정을 따로 발급받아 사용중인 것으로 알고있습니다. 실제 환경에서 테스트 할 때도 해외 카드로 진행하고 있습니다.
2. 제가 말씀을 좀 혼란스럽게 드린 것 같습니다. 죄송합니다. 디버그 모드에서 재현이 되지 않는다는 표현은 앱 실행 이후 내부에서 remote debug 환경으로 돌리면 재현이 되지 않는다는 말이었습니다. apk로 빌드하거나 안드로이드 스튜디오에서 실행해도 재현이 됐습니다.
3. 원본 소스로 롤백해도 재현이 됩니다. 모듈 코드를 수정한 이유는 `iamportUrl.isAppUrl()`을 포함하는 조건문 때문에 **웹뷰 환경**에서는 주석에 명시된대로 `react-native-webview 버전이 v10.8.3 이상`일 때 `무조건 onShouldStartLoadWithRequest를 true 처리하기 때문에`의 문제에 대한 코드를 실행하지 않기에 해당 코드만 `if (iamportUrl.isAppUrl())`의 분기 안쪽에서 바깥쪽으로 이동하였습니다.

감사합니다.

**Comment by marsland83** [comment]
저도 같은 에러가 발생하고 있네요.
예전부터 발생하는 고질적인 문제인것 같은데 빠르게 확인 후 수정이 필요할 것 같습니다.
