### ISSUE TITLE
iOS 결제시 앱 튕김 현상 문의드립니다~

### ISSUE THREAD

**Issue by 0strich** [iamport/iamport-react-native#68]
안녕하세요~ iOS 개발중 ISP 결제 후, 앱이 꺼지는 현상이 있어서 문의드립니다~
안드로이드에서는 현재 결제가 잘 되는 상태입니다~
답변 주시면 감사하겠습니다 ^^

ps, 캡쳐사진 보내드립니다
![스크린샷 2020-09-21 오후 1 37 28](https://user-images.githubusercontent.com/33608588/93733281-d4049300-fc0f-11ea-9d78-48b5383b7205.png)

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

앱이 꺼진다는 것이 ISP 앱이 꺼진다는 말씀이실까요?
첨부주신 두번째 사진 하단에 명시되어있는 것과 같이
ISP앱은 결제 인증이 끝나면 X초후 자동으로 앱이 꺼지도록 구현되어 있습니다.

아래와 같이 <IMP.Payment /> 컴포넌트 렌더링 시, 결제 데이터에 app_scheme값을

```
...
<IMP.Payment
  data={{
    ...
    app_scheme="귀하의_앱_URL_Scheme을_적어주세요"
  }}
/>
```

[info.plist 파일에 선언한 귀하 앱의 커스텀 URL Scheme](https://github.com/iamport/iamport-react-native#1-app-scheme-%EB%93%B1%EB%A1%9D)과 같은 값으로 보내시면
X초후 자동으로 ISP 앱이 종료된 후, 본래 귀하의 앱으로 정상적으로 돌아갑니다.

감사합니다.

**Comment by 0strich** [comment]
안녕하세요~ 답변주셔서 감사합니다
현재 안드로이드에서는 app_scheme 속성이 기입되어 있고, 안드로이드는 동작이 잘 됩니다~
iOS url_scheme 을 따로 적어줘야 하는 걸까요??

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

네 맞습니다.
[IOS 설정하기](https://github.com/iamport/iamport-react-native/blob/HEAD/manuals/SETTING.md)를 참고하셔서
필요한 설정을 마쳐주시길 바랍니다.

감사합니다.

**Comment by 0strich** [comment]
넵 문제 해결 됬습니다. 감사합니다~!
