### ISSUE TITLE
신용카드 카드선택 더보기 없애기 문의

### ISSUE THREAD

**Issue by 0strich** [iamport/iamport-react-native#69]
안녕하세요~ 모듈 사용 문의 드립니다

아래와 같이 더보기를 클릭하면 카드종류가 몇가지 더 나오는데 더보기 기능을 없애고 처음에 있는 카드목록만 노출시킬 수 있을까요?
혹은 노출시킬 수 있는 카드 종류를 개발자가 고를수 있나요??

![스크린샷 2020-09-22 오전 10 43 08](https://user-images.githubusercontent.com/33608588/93837389-dc68d680-fcc0-11ea-95ab-e3013fd352e7.png)

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

해당 문의는 PG설정과 관련되어있어 이메일 주소 남겨주시면 안내드리도록 하겠습니다.

감사합니다.

**Comment by 0strich** [comment]
gee8196@gmail.com 입니다 감사합니다~
