### ISSUE TITLE
[9000]GoodsName 필드값이 누락되었습니다

### ISSUE THREAD

**Issue by Leehee1on** [iamport/iamport-react-native#70]
alipay를 테스트 해보는 도중,
필드값이 누락 되었다고 나옵니다.
혹시 인증서라던지 뭘 받아야하나요?
다른 가이드라인이 있나요?

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

정확히 어떤 단계에서 해당 오류가 발생되시나요?

- 알리페이 결제창이 호출되지 않고 바로 콜백 함수가 호출됨
- 알리페이 결제창은 호출되나, 이후 단계(정확한 단계를 알려주세요)에서 결제가 진행되지 않고 콜백 함수가 호출됨

또한 해당 오류건이 발생한 imp_uid(아임포트 번호, [아임포트 관리자 페이지](https://admin.iamport.kr) > 결제승인내역에서 확인 가능)를 알려주시면 로그를 조회해보겠습니다.

감사합니다.

**Comment by Leehee1on** [comment]
알리페이 결제창이 호출되지 않고 바로 콜백 함수가 호출됩니다
imp_531498599894

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

담당 부서에 해당 이슈 전달했으니, 확인되는대로 안내드리도록 하겠습니다.

감사합니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

알리페이의 경우 주문명(`name`)에 **영문만 허용**되는 것으로 확인됐습니다.

이와 같은 점을 방지하기 위해 정규식으로 영문이 아닌 문자들을 모두 제거했을때 그 결과가 공란이면
`goods`라는 기본값을 지정해서 우선 결제창은 호출 되도록 수정하였습니다.
다만 크리티컬한 것 같지는 않으므로 다른 이슈 사항이 있을때 함께 배포할 예정입니다.

이용에 참고 부탁드립니다.
감사합니다.
