### ISSUE TITLE
URIError: URI malformed 

### ISSUE THREAD

**Issue by travelai-lab** [iamport/iamport-react-native#73]
결제 완료후 URIError: URI malformed 가 webview에서 발생합니다. 
특정 결제에서만 일어나는 문제인거 같은데 원인을 모르겠습니다.

"iamport-react-native": "^1.5.1",
"react-native-webview": "10.8.2",

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

보다 자세한 상황 파악을 위해 해당 이슈가 발생하는 상황에 대한 정보가 더 필요해 보입니다.
아래 정보를 알려주시면 디버깅에 도움이 될 것 같습니다.

- OS 종류: 안드로이드 / IOS / 둘다
- 해당 결제건의 imp_uid([아임포트 관리자페이지](https://admin.iamport.kr) >  결제 승인 내역에서 확인 가능, 많이 제공될 수록 좋음)
- 해당 현상이 나타나는 정확한 시점(결제 완료라고 하셨는데, 재현되는 동영상을 첨부 부탁드립니다.)
- 해당 현상이 재현될때 debugger-ui나 터미널에 찍히는 로그

감사합니다.

**Comment by travelai-lab** [comment]
@SoleeChoi 

OS는 IOS/Android 둘다 발생하며   결제 승인 자체에서는 문제가 없으나 완료후 에 URL 에서 WebView decoding 에서 url malformed 이 발생합니다.
정확한 정보는 저희도 확인할 수 없네요.

확인한 사항은 param.name 에  % 가 포함된 문자열을 넣었을때 100% 발생합니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

관련 내용 확인 및 조치 후 이번주 중으로 꼭 안내드리도록 하겠습니다.

감사합니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

확인 결과 모든 PG사 / 결제수단 / 카드사에서 발생하는 문제는 아닌 것 같아서
(예를 들면, KCP - 비씨카드(ISP) 결제시 정상)
고객님이 테스트하고 계신 PG사와 결제 수단(신용카드라면, 카드사까지) 알려주시면 디버깅에 도움이 될 것 같습니다.

감사합니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

말씀하신 내용은 버그로 확인되었으며,
해당 버그를 수정해 [v1.6.0](https://github.com/iamport/iamport-react-native/tree/v1.6.0)에 반영하였으니 확인 부탁드립니다.
v1.6.0은 feature 브랜치에 반영해둔 2가지 추가 기능까지 함께 반영되어 있는 점 유념해주시길 바랍니다.
자세한 내용은 [버전 정보](https://github.com/iamport/iamport-react-native/blob/master/manuals/VERSION.md)를 참고해주세요.

감사합니다.
