### ISSUE TITLE
비씨카드 결제 시에 자동으로 결제 완료 상태로 넘어가지 않습니다

### ISSUE THREAD

**Issue by nab5m** [iamport/iamport-react-native#74]
callback이 실행되지 않습니다

**[실행환경]**
기종: LG G7 Think Q

"iamport-react-native": "1.4.2",
"react": "16.9.0",
"react-native": "0.61.5"

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

저희가 동일한 기기(LG G7 ThinkQ)는 없어 다른 기기(갤럭시 S20)로 테스트 해 본 결과 정상 동작하여,
혹시 아래와 같이 시도해보시고도 같은 증상이 반복 되시는지 확인 부탁드립니다.

- iamport-react-native 모듈을 최신 버전(v1.5.2)로 업데이트
- 다른 기기로 테스트

위와 같이 하시고도 같은 증상이 반복 되시는 경우, 원활한 디버깅을 위해 아래 정보를 추가로 알려주시길 바랍니다.

- 테스트 중이신 PG사
- 해당 결제건의 imp_uid(아임포트 관리자 페이지 > 결제 승인 내역서 확인 가능)
- IOS에서도 같은 증상이 반복되시는지 여부

감사합니다.
