### ISSUE TITLE
예제소스에 나와있는 tierCode의 용도가 궁금합니다.

### ISSUE THREAD

**Issue by kyujun** [iamport/iamport-react-native#83]
공백으로 보냈을때는 정상적인 결제 동작이 이루어지지만 임의의 텍스트를 넣었을 경우 

 {"error_code": "F1001", "error_msg": "등록되지 않은 사용자 또는 등록되지 않은 PG정보입니다.", "imp_uid": null, "merchant_uid": "mid_1608537565690", "success": false}

해당 에러가 나옵니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

`tierCode`는 예제 코드의 주석에 나와 있는 대로 에이전시 기능 사용자에 한해 제공되는 파라미터입니다.
여기서 에이전시란, 여러 개의 서브 가맹점을 운영하고 있는 최상위 가맹점을 의미합니다.

아임포트 관리자페이지에 서브 가맹점 개수만큼 일일이 가입하는 대신
하나의 계정(가맹점 식별코드)로 모든 서브 가맹점을 관리하며, 각 서브 가맹점은 `tierCode`로 구분됩니다.

즉, 각 서브 가맹점은 가맹점 식별코드가 모두 동일(최상위 가맹점의 값)하기 때문에
결제창 호출시 `userCode`값은 최상위 가맹점의 값과 동일한 값을 전달하고 `tierCode`에 각자의 `tierCode`값을 전달하면
해당 가맹점의 PG설정 정보로 결제가 됩니다.

에이전시 기능은 요청한 사용자에 한해 제공되기 때문에
에이전시 기능을 사용하지 않는 사용자가 tierCode를 전달할 경우
고객님이 보시는 바와 같이 에러 메시지가 전달되며 결제창이 호출되지 않으니 이용에 참고 부탁드립니다.

감사합니다.
