### ISSUE TITLE
iOS에서 Imp.payment 뷰가 화면을 넘어서 나오는 문제

### ISSUE THREAD

**Issue by eunzihong** [iamport/iamport-react-native#85]
안녕하세요.  
현재 아임포트 페이를 추가하여 앱내 결제를 사용하려 하고 있습니다.
iOS 기기(iPhone 12 mini, pro)에서 테스트 할 때, 결제 화면 비율이 기기에 비해 세로 비율이 너무 길어서 화면 상하가 가리는 문제가 발생합니다.    

화면 뷰 스타일을 customize 할 수 있는 방법이 있나요? 없다면 화면 뷰 세로 비율을 조정해주시기를 부탁드립니다.
감사합니다.    

![IMG_1878](https://user-images.githubusercontent.com/43216580/103973498-e1d82700-51b2-11eb-8755-15b8e009dbf8.PNG)

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

답변이 늦어 대단히 죄송합니다.
말씀하시는 바가 이해를 제가 제대로 이해하지 못한 것 같은데,
기기의 세로 길이 < PG사 결제창 전체 화면 길이이기 때문에
세로로 스크롤이 생기신다는 말씀이실까요?

혹시 제가 이해한 것이 맞다면 세로 스크롤 없이 전체 화면을 축소해야하는데...
그러면 가로 길이도 동시에 축소가 될테고 모든 크기가 작아져서 유저의 경험을 해칠 것으로 염려됩니다.
그리고 무엇보다 중요한 것은 기술적으로 쉽지 않을 것으로 생각되는데,
일단 PG사의 결제창이 뜬 순간 렌더링 되는 화면은 PG사에서 작성한 페이지(html)이기 때문에
기술적으로 가능하다고 하더라도 저희(아임포트)가 코드(CSS 등)를 수정할 수 없습니다.

이용에 참고 부탁드립니다.
혹시 제가 이해한 내용과 다른 말씀을 하신 것이라면 보다 자세하게 설명해주시길 부탁드립니다.
감사합니다.
