### ISSUE TITLE
React-Native에서 사용

### ISSUE THREAD

**Issue by brandonra97** [iamport/iamport-react-native#86]
안녕하세요! 이렇게 유용한 library를 만들어주셔서 감사합니다 :)

다름아니라 설정 방법을 ios 는 xcode를 통해, android는 androidX를 통해하라고 알려주셨는데 이 모듈을 xcode나 androidX를 안쓰고 그냥 react-native에서 사용하고 싶으면 어떻게 하면되나요? 예시에 나와있는데로 그저 JSX component처럼 쓰면 되는것인가요? 현재 visual studios를 ide로 사용하고있습니다.

제가 react-native을 최근에 시작한지라 제가 모르는거일수도있지만 react-native만 사용해서 application을 만들때는 이 모듈을 어떻게 연동시키는지가 햇갈립니다 :( 특히 ios의 부분이 햇갈립니다..

도움주시면 정말 감사하겠습니다 ㅜㅜ

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

결제 프로세스(예) 신용카드)는 대개 아래와 같이 진행됩니다.
(카드 종류나 PG사에 따라 약간의 차이가 있을 수 있음)

귀하의 앱에서 결제하기 버튼 클릭 -> PG사 결제창 렌더링 -> 카드 종류 선택(예) 앱  카드인 경우) ->
카드사 앱으로 이동 -> 카드 인증(비밀번호 입력 등) -> 귀하의 앱으로 복귀 ->
최종 확인 버튼 클릭 -> 결제 프로세스 종료 -> 콜백 함수 호출

이때 귀하의 앱에서 서드 파티 앱(카드사  앱, 간편결제 앱 등)으로 이동하기 위해서는
**네이티브 단 코드(안드로이드는 Java, IOS는 Objective-C)가 반드시 필요**합니다.
이외에 추가로 현재 보고 계신 매뉴얼에 기재되어 있는 바와 같이
각각의 안드로이드/IOS 프로젝트에 추가적인 설정이 필요합니다.
EXPO 환경이라고 하더라도 EJECT가 필수인 이유입니다.

EXPO가 아닌 기본 RN으로 앱을 만드시면 (`npx react-native init`) 자동으로 ios 폴더와 android 폴더가 생성되기 때문에
매뉴얼대로 진행해주시면 되며
EXPO환경인 경우에는 [별도 매뉴얼](https://github.com/iamport/iamport-react-native/blob/master/manuals/EXPO.md)을 참고해주시길 바랍니다.

감사합니다.
