### ISSUE TITLE
휴대폰 본인인증 문자

### ISSUE THREAD

**Issue by brandonra97** [iamport/iamport-react-native#88]
안녕하세요! 저번에 한번 질문했던 유저입니다. 친절한 답변 덕분에 별 탈없이 library를 사용하기시작할수있었습니다! 다만 궁금한점들이 몇가지있어서 이렇게 글 남깁니다.

**1) 본인인증 휴대폰 문자발송**
저는 현재 휴대폰 본인인증 기능을 모바일엡에다가 구현할려고 iamport-react-native를 찾게되었습니다. 즉 많은 어플에서 본인인증하듯이 전화번호, 이름, 통신사 등등을 입력후 PASS 또는 문자 메세지를 통해 인증번호를 발급받아서 인증하는 기능을 추가하고싶습니다. github에 올려주신 예시와 가이드, example 코드, documentation들까지 살펴봤는데 이 인증번호,PASS 부분이나, 흔히 보이는 휴대폰 본인인증 화면을 어떻게 유저에게 보여주는지가 안나와있습니다. 
_https://docs.iamport.kr/tech/mobile-authentication#add-library_
^위에 링크 들어가면 나오는 통신사 선택 본인인증 화면을 뜻하는것입니다.

제가 예제에서 찾은건 certificationTest에서 form을 사용해 통신사, 전화번호, 이름 등등을 받아 certification페이지에다가 데이터 를 넘겨 그 페이지에서 <IMP.Certification..를 사용해서 iamport에다가 API 콜을 하는것같습니다. 그후 response를 CertificationResult 스크린으로보내, 성공했으면 imp_uid를 보여주고 아니면 에러를 보여주는것같습니다. 이 과정중에 인증번호,PASS 부분은 어디로 사라진것인가요? 왜 휴대폰 본인인증 화면이 안 뜨는것인가요?

**2) imp_uid**
제가 웹의 가이드를 본결과 imp_uid를 받으면 그걸 사용해서 다른 api 콜을 통해 정보를 얻는걸로 알고있습니다. 여기에서는 예제나 documentation에 그런 정보가없던데 어떻게 되는것인가요?

**3) 가맹점 식별코드**
만일 이 library를 사용해서 본인인증을하고싶으면 돈을내야하는건가요? 이 어플이 app store에 올려질때 금융문제는 어떻게되는것인가요?

감사합니다!

**Comment by brandonra97** [comment]
그리고 한가지 더 말씀드릴게있는데 expo예제를 실행할때 문제가있습니다 :(

가이드에 나온데로 따라서 expo start을하게되면 이런식에 log가 나옵니다:
"""
Starting project at /Users/Brandon/Desktop/AppDevelopment/iamport-react-native/exampleForExpo
Expo DevTools is running at http://localhost:19002
Some of your project's dependencies are not compatible with currently installed expo package version:
 - react-native-gesture-handler - expected version range: ~1.3.0 - actual version installed: ^1.4.1
 - react-native-webview - expected version range: 7.0.5 - actual version installed: 11.0.0
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo install [package-name ...]
Starting Metro Bundler
Your native app is running at expba40064ef55f4312b9da861780a9b781://172.30.1.48:19000
Logs for your project will appear below. Press Ctrl+C to exit.
"""

일단 기본적으로 expo를 부르면 주로 나오는 log들과 다릅니다. 일단 qr코드가 생성이 바로안되있고, localhost metrobundler manager도 바로 안열리고, "your native app is running at ..."이라는 처음 보는 말들도있습니다. 이걸 무시하고 localhost:19002로가서 나와있는 qr코드로 expo앱을 실행할려하면 핸드폰에서 실행불가로 나옵니다..

제가 무언갈 잘못하고있는건가요?

감사합니다!

**Comment by brandonra97** [comment]
지금 현재로서는 IMP를 가이드에 나온대로 import한후 예제와 똑같이 만들어 실행해봤습니다. 실행결과, <IMP.Certification.. 하는 화면에 들어가면 loading스크린이 한 0.1초 보인후 흰색 스크린만 계속 보입니다. 

callback function이 불러지지않는것같습니다. 여기에다가 페이지가 어떻게 로딩되는지 실험해볼려고 <View>랑 <Text>를 위에다가 넣었는데 이 코드가 추가되니 아예 expo앱이 에러로 종료하게됩니다.

제가 무언갈 잘 못하고있는건가요??

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

**1) 본인인증 휴대폰 문자발송**
일단 본인인증 연동 과정은 이해하고 계신 플로우가 맞습니다.
`<IMP.Certification />` 컴포넌트가  다날의 본인인증 창을 렌더링하고 문자 / PASS 인증 등은 모두 다날의 본인인증 창에서 이루어집니다.
즉, 다날이 개발한 것이라고 보시면 됩니다.
아임포트는 단순히 다날이 개발한 API 스펙에 맞게 요청을 보내고 받는 중간 다리 역할을 하고 있습니다.

현재는 <IMP.Certification /> 컴포넌트가 화면이 안뜨신다고 했는데 혹시 PG 설정이 제대로 되어있으실까요?
다날 휴대폰 본인인증은 **통신사 정책에 따라 테스트모드 설정이 불가능**합니다.
반드시 다날과 실 계약 후 운영 모드의 PG 설정 값을 전달 받아
[아임포트 관리자페이지](https://admin.iamport.kr) > 시스템설정 > PG설정(일반결제 및 정기결제)에 설정 후에만 이용 가능하십니다.

이렇게 운영모드가 설정된 아임포트 관리자페이지 계정의 `가맹점 식별코드`(시스템설정 > 내정보에서 확인 가능)를
`<IMP.certification />` 컴포넌트의 `userCode`에 넣어주셔야 합니다.
현재 예제 코드에는 테스트가 가능한 가맹점 식별코드가 적용되어 있으니
단순히 테스트를 해보고 싶으시다면 [테스트 앱](https://github.com/iamport/iamport-react-native/tree/master/exampleForExpo)을 돌려보시길 바랍니다.

또한 EXPO 환경이신 것 같은데 EXPO 환경에서 `iamport-react-native` 모듈 연동은 [별도의 문서](https://github.com/iamport/iamport-react-native/blob/master/manuals/EXPO.md)를 참고해주시길 바랍니다.

**2) imp_uid**
이후 과정은 **백엔드 단에서 발생하는 로직**이기 때문에 `iamport-react-native` 문서에는 안내되어 있지 않은 점 양해 부탁드립니다.
(프론트 단에서는 CORS 이슈로 아임포트 REST API를 호출할 수 없으며 앱은 브라우저 영역이 아니므로 CORS 이슈는 없으나
REST API를 호출할때 필요한 액세스 토큰을 인증 받기 위해 `REST API KEY`와 `REST API SECRET`키를 사용하실텐데
해당 값이 노출되는 것은 치명적이기 때문에 모든 아임포트 REST API 호출은 백엔드 단에서 하도록 강력히 권장하고 있습니다.)

현재 이해하고 계신 대로 콜백 함수에서 본인인증 성공시 아임포트 번호(`imp_uid`)로 [본인인증 내역 조회 API](https://api.iamport.kr/#!/certifications/getCertification)를 호출하시면 됩니다만,
위에 안내 드린 바와 같이 REST API 호출은 백엔드 단에서 해야 하기 때문에
가맹점 웹서버로 HTTP 요청을 보내시면 됩니다.

즉, 가맹점 클라이언트(콜백 함수) -> 가맹점 웹서버 -> 아임포트 웹서버라고 보시면 됩니다.

**3) 가맹점 식별코드**
앞서 1번 문의에서 안내 드린 바와 같이 다날 - 휴대폰 본인인증(휴대폰 본인인증은 다날 PG사만 제공함) 서비스는
운영모드만 사용 가능하기 때문에 반드시 다날과 PG 계약을 맺어야 합니다.
또한 휴대폰 본인인증 1건당 과금이 됩니다만, 자세한 내용은 cs@iamport.kr로 문의 부탁드립니다.
참고로 이는 가맹점과 PG사간 계약을 통해 차후 정산 받는 방식이라 앱 스토어에 올라갈때 따로 금융 문제(?)는 없습니다.

**4) EXPO 앱 종료**
PG설정을 완료하시고 [EXPO 환경에서 아임포트 연동하기](https://github.com/iamport/iamport-react-native/blob/master/manuals/EXPO.md)를 참고하시어
[EXPO용 예제 프로젝트](https://github.com/iamport/iamport-react-native/tree/master/exampleForExpo)와 같이 구성하셨음에도
동작하지 않으신다면 문의 부탁드립니다.

또한 debugging을 통해 다른 부분에서 스크립트 에러가 나는 곳은 없는지
콜백 함수에서 로직 위에 바로 response를 호출(`function (response) { console.log(response); }`)하셨을때 무엇이 호출되는지
(혹시 response.error_msg에 전달되는 값은 없으신지 등)을 확인해보시길 바랍니다.

감사합니다.
