### ISSUE TITLE
expo예제

### ISSUE THREAD

**Issue by brandonra97** [iamport/iamport-react-native#89]
expo예제를 실행할때 문제가있습니다 :(

가이드에 나온데로 따라서 expo start을하게되면 이런식에 log가 나옵니다:
"""
Starting project at /Users/Brandon/Desktop/AppDevelopment/iamport-react-native/exampleForExpo
Expo DevTools is running at http://localhost:19002
Some of your project's dependencies are not compatible with currently installed expo package version:

react-native-gesture-handler - expected version range: ~1.3.0 - actual version installed: ^1.4.1
react-native-webview - expected version range: 7.0.5 - actual version installed: 11.0.0
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo install [package-name ...]
Starting Metro Bundler
Your native app is running at expba40064ef55f4312b9da861780a9b781://172.30.1.48:19000
Logs for your project will appear below. Press Ctrl+C to exit.
"""
일단 기본적으로 expo를 부르면 주로 나오는 log들과 다릅니다. 일단 qr코드가 생성이 바로안되있고, localhost metrobundler manager도 바로 안열리고, "your native app is running at ..."이라는 처음 보는 말들도있습니다. 이걸 무시하고 localhost:19002로가서 나와있는 qr코드로 expo앱을 실행할려하면 핸드폰에서 실행불가로 나옵니다..

제가 무언갈 잘못하고있는건가요?

감사합니다!

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

에러 메시지에 나와있는 대로
현재 고객님의 컴퓨터에 설치되어 있는 EXPO 버전이
`exampleForExpo` 앱이 dependent한 `react-native-gesture-handler`와 `reacvt-native-webview` 패키지의 버전과 호환이 되지 않는 것 같습니다.
저희가 해당 예제 프로젝트를 만든지 오래되어서 아마 참조하고 있는 패키지들의 버전이 낮아서 발생하는 문제인 것 같습니다.

고객님께서 EXPO 버전을 낮출수도 없고 저희가 해당 앱을 업그레이드 하는데는 시간이 다소 소요될테니
급하신대로 일단 앞선 문의에 안내드린대로 다날과 계약 후 PG모듈 설정을 해보시고
콜백 함수에서 로그를 출력해보시면서 다시 테스트 해보시길 바랍니다.

감사합니다.
