### ISSUE TITLE
iOS 에서 "Asset not found" 에러

### ISSUE THREAD

**Issue by ssinss** [iamport/iamport-react-native#9]
iOS 디바이스에서 실행시 결제는 정상적으로 작동하나 결제 후 결제 완료 페이지 나옴 -> 완료 클릭 -> 하얀 배경에 "Asset not found" 메세지만 뜨고 더 이상 진행이 되질 않습니다. 콜백 역시 호출 하지 않는 듯 보입니다.
문서에 있는 '아임포트 asset 추가하기' 내의 해당 asset 들은 모두 추가된 상태이고 라이브러리 버전은 1.0.6 입니다.

![file](https://user-images.githubusercontent.com/1166723/52547915-121fbb00-2e0e-11e9-8337-534c3e98f5f7.jpg)

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트입니다.
말씀해주신 `완료버튼`이 있는 `결제완료페이지`는 사용자께서 직접 구현하신 컴포넌트인가요?
아임포트 모듈을 호출하는 코드(결제 파라미터와 콜백함수 포함)를 적어주시면 보다 디버깅이 수월할 것 같습니다.
감사합니다.

**Comment by ssinss** [comment]
죄송합니다. 콜백은 정상 작동되는걸로 확인 됩니다.

아래는 해당 컴포넌트의 코드 입니다.

```javascript
import IMP from 'iamport-react-native';
import React, { Component } from 'react';

export default
class Iamport extends Component {
  iamportCallback(response) {
    console.log('callback', response)
  }

  render() {
    return (
      <IMP.Payment
        userCode='imp42868000'
        data={{
          amount: 5000,
          app_scheme: 'testapp',
          buyer_email: 'test@test.com',
          buyer_tel: '01000001111',
          merchant_uid: '35278',
          name: '아이템',
          pay_method: 'card',
          pg: 'jtnet'
        }}
        callback={this.iamportCallback}
        loading={{
          message: '잠시만 기다려주세요... 결제를 진행중 입니다.'
        }}
      />
    )
  }
}
```

아래는 결제 페이지의 스크린샷 입니다.
![img_2694](https://user-images.githubusercontent.com/1166723/52621885-c3485300-2eeb-11e9-8622-bca436456beb.JPG)

여기에서 완료를 누르면 위 "Asset not found" 페이지가 뜨게 됩니다.

**Comment by SoleeChoi** [comment]
보여주신 화면은 아임포트가 기본적으로 제공하는 결제완료 페이지입니다.
사용자께서 결제결과를 보여주는 컴포넌트를 따로 직접 작성하신 후,
콜백함수에서 이 컴포넌트로 라우터 변경을 하셔야 합니다.
이는 [아임포트 RN모듈 콜백 설정하기](https://github.com/iamport/iamport-react-native/blob/master/CALLBACK.md) 메뉴얼에서 확인해보실 수 있습니다.
또한 아임포트 RN모듈에 내재되어있는 예제 프로젝트도 참고하실 수 있습니다.
감사합니다.

**Comment by ssinss** [comment]
제가 문서를 제대로 보질 못했네요;

답변 감사드립니다! 이 이슈는 클로즈 하겠습니다.
