### ISSUE TITLE
PG사 데이터를 params로 넘기는데 에러가 발생합니다

### ISSUE THREAD

**Issue by borijuyeong** [iamport/iamport-react-native#90]
`TypeError: pg.startsWith is not a function. (In 'pg.startsWith('smilepay')', 'pg.startsWith' is undefine`

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

<IMP.Payment /> 컴포넌트 호출시 결제 데이터(data) prop을 전달하실때 pg값을 어떤 값으로 보내고 계실까요?
pg값은 pg사 식별 코드 또는 pg사 식별 코드.pg 상점 아이디 형태의 문자열(string)만 허용됩니다.

예를 들어 KG이니시스 - 빌링결제 - 테스트모드의 경우 유효한 pg값은 html5_inicis. INIBillTst가 됩니다.
만약, 해당 PG모듈 설정이 기본값으로 설정되어있는 경우엔 pg값에 html5_inicis만 넣어주시면 됩니다.

허용되는 유효한 pg사 식별 코드 값은 [여기](https://github.com/iamport/iamport-react-native/blob/master/src/constants/index.js#L3)를 참고해주세요.

감사합니다.
