### ISSUE TITLE
나이스페이 신 버전 적용 요청드립니다

### ISSUE THREAD

**Issue by nab5m** [iamport/iamport-react-native#91]
나이스페이를 이용할 때 간편결제 옵션 선택 시 "네이버페이"나 "카카오페이"가 보인다고 합니다. 현재는 그렇지 않아서 나이스페이 측의 답변 공유드립니다.

> 가맹점측에서는 구버전을 사용중이여서 간편결제 이용시 호환이 안되는것으로 보입니다.
> 
> 나이스페이 인증 요청 url이  현재 제공하는 인증 요청 URL : https://web.nicepay.co.kr/v3/webstd/js/nicepay-2.0.js 이 아닌 낮은버전이라면 해당 url 으로 변경부탁드립니다.
> 
> (예시 : 구버전 나이스페이 인증 요청 URL : https://web.nicepay.co.kr/flex/js/nicepay_tr_utf.js )

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

기존 사용자와의 호환성을 위해 나이스페이 - 모바일 구/신버전을 모두 제공하고 있으며
신버전 적용을 위해서는 아래와 같이 niceMobileV2를 true로 설정해주셔야 합니다.

```javascript
<IMP.Payment
  {...}
  data={{
    ...
    niceMobileV2: true
  }}
/>
```

이용에 참고 부탁드립니다.
감사합니다.

**Comment by nab5m** [comment]
감사합니다 :) 적용해볼게요 ! _ !
