### ISSUE TITLE
본인인증을 PASS 앱에서 마친 이후 홈 화면으로 가는 이슈

### ISSUE THREAD

**Issue by smsmsmsmin** [iamport/iamport-react-native#92]
안녕하세요.

아임포트로 React Native 환경에서 본인인증을 진행하면서 PASS 인증 이후 홈 화면으로 가서 다시 개발하고 있는 앱으로 돌아와야 하는 번거로움이 있어 한번에 구성되도록 하려 문서를 찾아보다 app_scheme라는 옵션을 발견해서 추가해봤지만 해결되지 않아 이슈 남깁니다.

제가 사용한 코드입니다.
```tsx
 <IMP.Certification
      userCode="imp28177650"
      loading={<ActivityIndicator size="large" />}
      data={{ ...certificationData, app_scheme: 'scheme' }}
      callback={callback}
    />
```
certificationData에 있는 carrier, name, phone, min_age 모두 정상적으로 패싱되나, app_scheme만 정상적으로 처리되지 않습니다.

LSApplicationQueriesSchemes에 3사 PASS 앱 스키마 (tauthlink, uplusauth, ktauthexternalcall)도 추가했고, URL Types에 app_scheme에 들어가는 값도 추가 완료했습니다. (이미 딥링크로 사용하던 스키마입니다)

아래는 package.json 정보입니다.

    "react-native": "0.63.4",
    "iamport-react-native": "^1.6.2",
    "react-native-webview": "^11.2.3",

확인 부탁드립니다. 감사합니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

IOS - PASS앱에서 인증 완료 후 본래의 앱으로 복귀를 하기 위해서는
PASS앱이 복귀해야 할 URL Scheme값으로 시작하는 특정 URL(`예) example://`)을 호출해야 하는데,
PASS앱이 이러한 기능을 제공하고 있지 않아 사용자가 직접 복귀해야 합니다.
이는 아임포트가 제어할 수 없는 영역이기 때문에 수정이 불가능한 점 양해 부탁드립니다.

참고로 안드로이드의 경우에는 안드로이드 OS가 Activity Stack을 직접 제어하기 때문에
내 앱 -> PASS앱으로 이동한 경우 Stack의 최상위에 PASS앱이 있다가
인증이 완료되어 PASS앱이 Stack에서 POP되면 자동으로 내 앱이 띄워지는 것으로
마치 복귀가 되는 것처럼 보이지만, 기술적으로 봤을때 `복귀`한다고 말할 수는 없습니다.
같은 이유로 안드로이드라고 하더라도 내 앱 -> PASS앱 -> 강제로 홈 화면으로 이동 -> 다시 PASS앱 복귀 -> 인증 완료하면 내 앱으로 돌아오지 않고 홈 화면으로 돌아갑니다.

이용에 참고 부탁드립니다.
감사합니다.
