### ISSUE TITLE
안드로이드에서 외부 앱 연결이 안됩니다

### ISSUE THREAD

**Issue by oikkoikk** [iamport/iamport-react-native#98]
### 외부 앱 연결 오류

`iamport-react-native` : `v.1.6.3`
`react-native-webview` :` v.10.8.3`
`가맹점 식별코드(userCode) `: `imp86662034`

ios에서는 잘 되는데, 안드로이드에서는 외부앱으로 넘어가야하는 시점에서 callback함수를 호출하면서 다음과 같은 response가 옵니다.

```
Object {
  "error_code": undefined,
  "error_msg": "null is not an object (evaluating 'Iamport.getAppUrl')",
  "imp_success": false,
}
```

앞선 이슈에서도 나와있듯이, 링크 문제가 아닌가 하고 다시 한 번 살펴봤는데 링크는 제대로 되어있는 것 같습니다.

+) 추가 질문
현재 expo에서 eject한 후 아임포트 모듈을 사용하고 있는 것인데, eject 제대로 안되어서 이런 현상이 일어날 수도 있는 것인가요?
ios에서는 잘 작동해서 eject 문제는 아니라고 혼자 생각하고 있기는 한데, 앞선 이슈에서도 url 변환이 네이티브로 이루어진다고 하신 것 같아서 한 번 여쭤봅니다..!

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

해당 이슈는 expo 환경에서 eject가 제대로 되어있지 않아서 발생하는 문제로
expo 환경에서 아임포트 모듈을 연동하고 계시다면 eject는 필수입니다.

해당 오류는 [여기](https://github.com/iamport/iamport-react-native/blob/master/src/components/Payment/index.android.js#L11)에서 발생하고 있는 것으로 추정됩니다.
이 코드는 PG사 결제창에서 결제수단 선택 후 서드 파티 앱(카드사 앱, 간편결제 앱 등)으로 이동시 타게 되는데
이때 웹뷰와 서드 파티 앱간 이동 방식에 있어 안드로이드와 IOS에 차이가 있습니다.
안드로이드는 intent 데이터를 파싱해 올바른 URL로 변환해야 하기 때문에 [네이티브단 코드](https://github.com/iamport/iamport-react-native/blob/master/android/src/main/java/com/iamport/IamportModule.java#L40)를 사용하고 있고
IOS는 URL의 app sheme만으로 판단할 수 있기 때문에 [javascript 코드](https://github.com/iamport/iamport-react-native/blob/master/src/components/Payment/index.ios.js#L11)만으로 처리할 수 있습니다.

그렇다고 해서 IOS 연동시 eject가 필요하지 않느냐라고 문의주신다면 아닙니다.
그러니 eject를 하시고 다시 시도해주시길 바랍니다.

자세한 내용은 [엑스포에서 아임포트 연동하기](https://github.com/iamport/iamport-react-native/blob/master/manuals/EXPO.md) 문서를 참고해주시길 바랍니다.

감사합니다.

**Comment by oikkoikk** [comment]
eject를 다시 해도, 해당 현상이 고쳐지질 않습니다. 링킹도 전에 적어두신 '수동 링킹' 과정과 비교했을 때, 제대로 되어있는 것 같은데... 혹시 eject나 linking 이외의 원인은 없는건가요?

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

eject가 제대로 되어있다면 [앱 이름]/android/app/src/main/java/host/exp/exponent/MainApplication.java 파일의 getPackages 메소드에 IamportPackage가 포함되어있어야 하고
([exampleForExpo 관련 코드](https://github.com/iamport/iamport-react-native/blob/master/exampleForExpo/android/app/src/main/java/host/exp/exponent/MainApplication.java#L33))
AndroidStudio에서 프로젝트를 열으셨을때(Android Studio에서 [앱 이름]/android/app 폴더를 오픈)
아래와 같이 iamport-react-native 모듈이 포함되어 있어야 합니다.

![image](https://user-images.githubusercontent.com/42368261/113540945-25102d80-961c-11eb-91ed-294451f959fb.png)

안내주신 에러 내용을 보면 eject 및 linking이 제대로 되어있지 않아 발생하는 문제이기 때문에
위 두 가지 사항이 제대로 되어있으신지, 즉 eject 및 linking이 제대로 되어있는지 확인 부탁드립니다.
혹시 모르니 unlinking -> uninstall -> install -> linking도 추천드립니다.

감사합니다.
